### ISSUE TITLE
[Question] is it published in the Jetbrains Plugins marketplace?

### ISSUE THREAD

**Issue by fmquaglia** [tomblachut/svelte-intellij#1]
I think it's not yet right?
What is still missing to make that happen?

**Comment by tomblachut** [comment]
I wanted to polish it a bit more before publishing. I'll upload it soon

**Comment by tomblachut** [comment]
https://plugins.jetbrains.com/plugin/12375-svelte waiting for approval

**Comment by fmquaglia** [comment]
Thank you so much @tomblachut 
I couldn't wait and cloned the repo and built it locally. Great work so far.
My kotlin-fu is poor but I'd love to help. 
Is there anything else I can do?

**Comment by tomblachut** [comment]
Definitely! There's a lot to do. BTW I'm learning Kotlin as I go. I'm a frontend developer by profession 😂 I'll write more issues during the week and tags related to complexity. 

From top of my head, proper support for svelte namespaced component's (#8) would be great. I spent some time on it today but couldn't overcome hurdle of special rules for said namespaces. All basic HTML tags aren't namespaced.

**Comment by fmquaglia** [comment]
OK, I'll try to catch up with Kotlin. If anything else crosses your mind feel free to tag me in an issue. 
Thanks for your work on this sir. <3

**Comment by tomblachut** [comment]
Definitely!
