### ISSUE TITLE
Incompatibility with EAP 2020.1

### ISSUE THREAD

**Issue by ArrowBaZ** [tomblachut/svelte-intellij#102]
Hello,

the plugin is flag as incompatible for the EAP 2020.1.

```
Plugin Error: The Svelte (id=dev.blachut.svelte.lang, path=~/Library/Application Support/JetBrains/WebStorm2020.1/plugins/svelte-intellij, version=0.12.0) plugin is incompatible (target build range is 192 to 201).
```
Is it possible to upgrade the target range ?

Regards,
Arrowbaz

**Comment by tomblachut** [comment]
I've noticed it too today :) I'll try to release update someday soon

**Comment by joshua1** [comment]
Hi @tomblachut This will be great , any chance today can be someday 🥇

**Comment by tomblachut** [comment]
No, we're having a crunch in my day job, gotta pay the bills @joshua1

**Comment by tomblachut** [comment]
New version should appear in Plugin Marketplace within 2 days, you can download it already here:

https://github.com/tomblachut/svelte-intellij/releases/tag/v0.12.1

Cheers
