### ISSUE TITLE
'}' expected, got '==='

### ISSUE THREAD

**Issue by theword** [tomblachut/svelte-intellij#104]
First of all, thank you for your great work. 

I am using webstorm and I have this piece of code written which I believe is valid. It runs and works correctly.

<script>
	let players = [];
</script>

{#if players.length === 0}
     <p>No Players</p>
{/if}

However, Webstorm yells at me saying " '}' expected, got '===' instead. "

ISSUE SOLVED: Old version of software.

**Comment by tomblachut** [comment]
Can I assume that your snipped was in fact

```
<script>
	let players = [];
</script>

{#if players.length === 0}
	No Players
{/if}
```

?

**Comment by theword** [comment]
Yes, that is correct. I should of been more clear.

**Comment by bravecow** [comment]
![image](https://user-images.githubusercontent.com/988471/73847047-30a47080-482e-11ea-9e31-55663dd86078.png)

no lint errors

**Comment by theword** [comment]
![Lint](https://user-images.githubusercontent.com/1483287/73993259-48a3ef00-4917-11ea-939c-820d3f9eb1d9.png)

Hmm maybe, something else is going on for me then...

**Comment by bravecow** [comment]
@theword try the same minimal example you posted here (and on my screenshot). And check if you are using the latest version of plugin 🤷‍♂

**Comment by tomblachut** [comment]
@theword This looks like a really old version of the plugin (attribute expressions aren't parsed). Please update to the latest version and it should work. 

I've checked it myself now and got the same result as @bravecow

**Comment by theword** [comment]
Ok yeah, that was it. I was on an earlier version of WS and it installed version 0.8.0. Having updated to 2019.3 now and getting version 0.12.0. The issue is now gone. Thanks for the great software!

**Comment by tomblachut** [comment]
Cheers
