### ISSUE TITLE
"A term expected" when trying to pass argument into style attribute

### ISSUE THREAD

**Issue by snowb1shop** [tomblachut/svelte-intellij#106]
Great plugin !

I have a problem when trying to pass an argument from script into svelte code

```
<script>
    export let buttonColor = "#a8b634";
</script>
<button style="background-color: {buttonColor}" >Button</button>
```

This will show an error in IDE from Svelte plugin: "A term expected".
Although the code works and it's the same as in the Svelte Tutorial example, which also causes it: 
https://svelte.dev/tutorial/dimensions

**Comment by tomblachut** [comment]
Hello, should be fixed in https://github.com/tomblachut/svelte-intellij/releases/tag/v0.12.1
