### ISSUE TITLE
Required plugin "Javascript"

### ISSUE THREAD

**Issue by zolotokrylin** [tomblachut/svelte-intellij#111]
For some reason, it requires this plugging. I am going to plugging section but I can not find via search the exact match for `Javascript` plugin.

![Screenshot 2020-04-30 at 1 09 45 PM](https://user-images.githubusercontent.com/1125014/80674368-426f7a00-8ae4-11ea-8a78-44cd270f8cfd.png)

**Comment by tomblachut** [comment]
JavaScript is a built in one, it won't show in Plugins page. It's bundled with IntelliJ Ultimate, WebStorm, PHPStorm etc. Can you show your about page? e.g:

![image](https://user-images.githubusercontent.com/615013/80685606-bbaca400-8ac7-11ea-9ef4-1f6348d3d8d5.png)

**Comment by zolotokrylin** [comment]
I use Community version.

![image](https://user-images.githubusercontent.com/1125014/80807922-f4946800-8bf0-11ea-8a92-fea025885235.png)

**Comment by tomblachut** [comment]
Yeah it doesn't work like that. IDEA Community doesn't bundle JavaScript, there's no way around it.

* If you want to use released version you need to load it in WebStorm, IDEA Ultimate etc. 
* If you want to develop the plugin there's `runIde` Gradle task that launches IDEA Ultimate for development purposes. You don't need to buy a license.

**Comment by zolotokrylin** [comment]
Thank you!
