### ISSUE TITLE
Does not recognize .svelte.erb

### ISSUE THREAD

**Issue by sedubois** [tomblachut/svelte-intellij#113]
Thanks for this very helpful IntelliJ IDEA plugin! It's been a pleasure to learn using Svelte using the IDEA thanks to this.

It handles *.svelte files very well, however it does not recognize .svelte.erb files as Svelte files (although this is [supported](https://github.com/rails/webpacker/pull/2411) by Webpacker). Could this somehow be supported?

**Comment by tomblachut** [comment]
Hi, thanks for the kind words.

Can you give me an example of `.svelte.erb`?

**Comment by sedubois** [comment]
@tomblachut the code below renders "hello from http://localhost:3000/" when run locally:

```svelte
// Hello.svelte.erb
<script>
  let host = "<%= ENV['HOST'] %>"
</script>

<p>hello from {host}</p>
```

**Comment by tomblachut** [comment]
I've opened this snipped in next version (#100) and it looks like this: 

<img width="405" alt="image" src="https://user-images.githubusercontent.com/615013/80912555-fddf1b00-8d3d-11ea-9651-329e22967e01.png">

I guess this is good enough, right?

**Comment by sedubois** [comment]
Yes the ERB syntax only seems partly recognized but at least the Svelte syntax seems good 👍
