### ISSUE TITLE
Component imports are being incorrectly marked as unused

### ISSUE THREAD

**Issue by asm0dey** [tomblachut/svelte-intellij#114]
Consider the following snippet:

```vue
<script>
    import { Button, Col, Row } from 'sveltestrap';
</script>

<Row>
    <Col>
        <Button color="primary" outline>Hello World!</Button>
    </Col>
</Row>
```
In this example the whole `import` line is marked as unused while being obviously used

```
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Licensed to JetBrains Team / Pasha Finkelshteyn
Subscription is active until December 10, 2020
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.5.19-1-manjaro
GC: ParNew, ConcurrentMarkSweep
Memory: 3987M
Cores: 16
Non-Bundled Plugins: com.jetbrains.upsource, com.github.jk1.ytplugin, com.perl5, woaini.liquibase.plugin, com.markskelton.one-dark-theme, org.intellij.scala, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, com.codota.csp.intellij, kotlintest-plugin-intellij, org.jetbrains.debugger.streams.kotlin, org.jetbrains.plugins.vue, dev.blachut.svelte.lang, lermitage.intellij.extra.icons
Current Desktop: KDE
```

**Comment by tomblachut** [comment]
Ah yes, re-exports don't work yet

Duplicated by #48

**Comment by asm0dey** [comment]
Why is it reexport?

**Comment by tomblachut** [comment]
Svelte compiles to default exports, which are recognized, but e.g. in case of npm libraries you usually want to create one module which re-exports everything else, like in case of `sveltestrap`

**Comment by ma13gagan** [comment]
It's still not working for me. I am using `WebStorm 2023.2.2` and plugin version `232.9921.36`. IDE is still marking reexport imports as unused.

![image](https://github.com/tomblachut/svelte-intellij/assets/65103311/d9826adb-366b-422d-a40a-11077c950efe)

**Comment by nekogochan** [comment]
idea is f\*cked in last time like s\*it. Got problem like this too.

idea version: Build #IU-232.10227.8, built on November 9, 2023

plugin version: 232.9921.36

![image](https://github.com/tomblachut/svelte-intellij/assets/44098718/a60a6706-15cd-48b9-9235-95cdd1e7d339)

![image](https://github.com/tomblachut/svelte-intellij/assets/44098718/10831e9d-7383-4fb9-b066-110fceb0846f)
