### ISSUE TITLE
Regressions in #100 unused store variable

### ISSUE THREAD

**Issue by shirotech** [tomblachut/svelte-intellij#116]
Sorry for reporting something that is in progress, but hopefully this may be helpful to you, in any case here it is. This is in regards to #100 

When a store is derived from a destructor and used with `$` prefix, it doesn't seem to register it as being "used".

Before:
<img width="678" alt="Screen Shot 2020-05-09 at 11 29 44 am" src="https://user-images.githubusercontent.com/1149825/81460435-b8f92f80-91e8-11ea-8cbb-fa69ff593756.png">

After:
<img width="705" alt="Screen Shot 2020-05-09 at 11 27 44 am" src="https://user-images.githubusercontent.com/1149825/81460439-bd254d00-91e8-11ea-9c2d-da2f3e9e2fb4.png">

Also keep up the great work, very promising plugin. 👍

**Comment by tomblachut** [comment]
> Sorry for reporting something that is in progress

This is helpful, don't hesitate next time :)

I don't really know what is happening yet. Store references was never programmed to be registered as used yet, "before" behavior looks like as a side effect.

Can you paste this code here as text?

**Comment by shirotech** [comment]
@tomblachut If that is the case I guess bug exists in "before" (master 90fb24f1)

What is happening I think is everything has been treated as "used", I've created a fresh new empty project to make sure there are no side effects e.g. referencing same variable names in other files. 

This can be observed below:
![Screen Shot 2020-05-10 at 1 00 38 am](https://user-images.githubusercontent.com/1149825/81477285-56407c00-925a-11ea-8689-f71e28dc3855.png)

Note that this is not the behaviour we want as opposed to a normal js file:
![Screen Shot 2020-05-10 at 1 01 33 am](https://user-images.githubusercontent.com/1149825/81477303-6b1d0f80-925a-11ea-824f-ea88eb093885.png)

After applying #100 (47eb7515) this has been resolved:
![Screen Shot 2020-05-10 at 1 02 43 am](https://user-images.githubusercontent.com/1149825/81477313-796b2b80-925a-11ea-8495-43879b22a70c.png)

Please feel free to close this, as I think once #100 has been merged, the "used" bug will resolve.
