### ISSUE TITLE
Chokes when there is an apostrophe in comments

### ISSUE THREAD

**Issue by shirotech** [tomblachut/svelte-intellij#119]
I'm using the latest from #100 

A really weird parsing issue.

before:
![Screen Shot 2020-05-26 at 8 16 23 am](https://user-images.githubusercontent.com/1149825/82845837-6d08f300-9f29-11ea-82f7-80db9cbd1f28.png)

after:
![Screen Shot 2020-05-26 at 8 16 45 am](https://user-images.githubusercontent.com/1149825/82845840-71351080-9f29-11ea-9d37-62fed182677c.png)

Notice when I remove the apostrophe, it works fine.

**Comment by tomblachut** [comment]
I admit that I underestimated that rewrite

**Comment by tomblachut** [comment]
This is really interesting, I left a bug in rules about counting braces and string literals.

Consider this snippet:

```svelte
<div>
    {
        'unclosed string literal inside expression
    }
</div>
```

script/style tags are an edge case
