### ISSUE TITLE
Electron Autocomplete?

### ISSUE THREAD

**Issue by vollpiin** [tomblachut/svelte-intellij#120]
I don't know if that's the right place for this issue, but I'm trying to use Electron with Svelte, when I try to require Electron package inside `<script>` tags I don't get any autocomplete, it works fine with `.js` files.

![Screenshot from 2020-06-03 02-27-46](https://user-images.githubusercontent.com/44704549/83585760-3c811480-a53a-11ea-92d6-c924895e0c71.png)

**Comment by tomblachut** [comment]
I think you need to use ESM imports inside Svelte, anyhow require syntax don't have any special support in this plugin.
