### ISSUE TITLE
Props shared with / passed to slot, more than one letter inside braces not being recognized

### ISSUE THREAD

**Issue by vatro** [tomblachut/svelte-intellij#122]
Hi,

this may be related to [#105](https://github.com/tomblachut/svelte-intellij/issues/105) 🤔

Given this setup: [see Svelte REPL](https://svelte.dev/repl/a4a9c258c85b4271b0057334938ff23a?version=3.23.2) 

Prop passed from / shared by Parent.svelte is not being recognized on the slotted component.
It compiles ok / works though.

![svelte-intellij-shared-slot-prop](https://user-images.githubusercontent.com/3778969/84670988-1b9bc480-af27-11ea-96b5-922f78d13723.gif)

Thanks & keep up the good work! ✊

**Comment by vatro** [comment]
... but if you do something like this ([see Svelte REPL](https://svelte.dev/repl/dce25f4949474620ae6f409801c69c96?version=3.23.2))

than it's ok:

![svelte-intellij-shared-slot-prop-works](https://user-images.githubusercontent.com/3778969/84672819-44bd5480-af29-11ea-9312-54e3e889e721.jpg)

**Comment by tomblachut** [comment]
I've checked it in [v0.13.0](https://github.com/tomblachut/svelte-intellij/releases/tag/v0.13.0) and it looks like it's working.

![image](https://user-images.githubusercontent.com/615013/89770497-245fdf80-daff-11ea-8cbf-e2adfd260d2f.png)

Please let me know if issue is still occurring.
