### ISSUE TITLE
Incompatibility with EAP 2020.2

### ISSUE THREAD

**Issue by ZaDarkSide** [tomblachut/svelte-intellij#126]
![image](https://user-images.githubusercontent.com/291278/85366722-9a4cbf00-b530-11ea-8988-1ae15416645f.png)

**Comment by zzwx** [comment]
https://github.com/tomblachut/svelte-intellij/pull/123 seems ready to fix this

**Comment by ZaDarkSide** [comment]
Yes, waiting for the merge, hopefully it will happen soon

**Comment by rbrzoska** [comment]
Could ypu merge it? :) we need it - in current eap this plugin is unusable

**Comment by tomblachut** [comment]
I'm gonna release a new version this week, thanks for your patience everyone.

**Comment by rbrzoska** [comment]
Still no update :)

**Comment by neron01** [comment]
Please do it)

**Comment by r00t3g** [comment]
Guys, as a temporary measure, I've packed a version with #123 merged in which I am using myself for the latest EAP, you can grab it and install manually from here: https://github.com/r00t3g/svelte-intellij/releases

**Comment by neron01** [comment]
@r00t3g Thanks a lot :)

**Comment by anstarovoyt** [comment]
@tomblachut any updates on this? We've released 2020.2 and it isn't compatible with the plugin

**Comment by tomblachut** [comment]
Hello, I had no energy to work on OSS lately, sorry for inconvenience.

@r00t3g thanks for a workaround!

@anstarovoyt damn I though I'll manage to fix it before a release, anyway I've submitted 0.12.2 for approval to Marketplace

**Comment by r00t3g** [comment]
> @r00t3g thanks for a workaround!

No problem! Thanks for your efforts in bringing the Svelte Support into IJ. Hoping to see #100 resolve :) I'd like to help, but my kotlin/java skills are not that good yet :( Try to find someone who could contribute among my mates, but no success yet.

Dropping my fork as unneeded.

**Comment by tomblachut** [comment]
Kotlin is easiest part of this 😅  I'm still trying to understand HTML specification with all its corner cases

Anyway I understand that everybody has limited time in a day, I'm not going anywhere and Svelte support will be sloooowly improved, it's just hindered by more exhausting times in my FT job
