### ISSUE TITLE
Svelte's latest typescript support

### ISSUE THREAD

**Issue by joshua1** [tomblachut/svelte-intellij#127]
Is there anything that can be used from the improvements mentioned in this svelte blog post: https://svelte.dev/blog/svelte-and-typescript to support svelte development using svelte-IntelliJ

**Comment by Atulin** [comment]
#124 and #32. Seems we need to wait.

**Comment by tomblachut** [comment]
I need to deduplicate issues somehow, closing this one.

To answer the question, whole `Svelte Language Server` going stable is an excellent news, integrating it will reduce required work a lot for initial support.
