### ISSUE TITLE
Webstorm 2020.2 update breaks plugin

### ISSUE THREAD

**Issue by gness1804** [tomblachut/svelte-intellij#128]
After upgrading to the 2020.2 version of Webstorm, this plugin no longer works. The specific error is: 

`Plugin Error: Plugin "Svelte" is incompatible (marked as broken).`

Tried:
* Disabling and reenabling the plugin
* Uninstalling and reinstalling the plugin
* Using the plugin on a second install of WS

I just noticed this today when after I installed the new version of WS. 

Thanks for your help with this! Great plugin, by the way -- it's a necessity for my work. 

<img width="639" alt="Screen Shot 2020-07-27 at 20 03 17" src="https://user-images.githubusercontent.com/17103851/88607411-cc2bd680-d044-11ea-929d-c1ffccf02b1f.png">

**Comment by r00t3g** [comment]
Hello. This has also been discussed in #126 and the temporary workaround is also there (not sure if it works with WS2020.2, however)

**Comment by tomblachut** [comment]
Sorry for the inconvenience.

Update will be available in the Marketplace when JB approves it (tomorrow?), you can also grab `.zip` here: https://github.com/tomblachut/svelte-intellij/releases/tag/v0.12.2

**Comment by tomblachut** [comment]
They are very fast 😀  https://plugins.jetbrains.com/plugin/12375-svelte/versions/stable/93053

**Comment by gness1804** [comment]
Thanks! 😄 👍
