### ISSUE TITLE
Import inserted in the template rather than in the script

### ISSUE THREAD

**Issue by unlocomqx** [tomblachut/svelte-intellij#129]
This is a tricky one
An auto-import is inserted in the template, it should be inserted in the script section
![2020-08-01_10-36](https://user-images.githubusercontent.com/793712/89098840-e9fd9080-d3e2-11ea-9d97-bfeaf2a6fa2e.png)

**Comment by tomblachut** [comment]
I have somewhat working solution on local branch but JB refactored this inspection in 2020.2 and I'm unsure how to proceed for now

**Comment by unlocomqx** [comment]
I don't even know if inspections are relevant to this issue, it's an auto-import so it's probably relevant to completion rather than inspection. Maybe I don't understand but here's a gif to alleviate any potential ambiguity

![Peek 2020-08-02 10-16](https://user-images.githubusercontent.com/793712/89119845-3b705300-d4a9-11ea-9188-9dab727058f1.gif)

**Comment by unlocomqx** [comment]
The shortest way I think is to change the behaviour of `ES6ImportPsiUtil::findAnchorToInsert`

![2020-08-02_10-24](https://user-images.githubusercontent.com/793712/89120006-64ddae80-d4aa-11ea-8ee1-1e97dca98883.png)


```
findAnchorToInsert:236, ES6ImportPsiUtil (com.intellij.lang.ecmascript6.psi.impl)
findPlaceForImport:204, ES6ImportPsiUtil (com.intellij.lang.ecmascript6.psi.impl)
findPlaceByModuleName:174, ES6ImportPsiUtil (com.intellij.lang.ecmascript6.psi.impl)
findPlaceAndInsertES6Import:460, ES6CreateImportUtil (com.intellij.lang.ecmascript6.psi.impl)
createImportOrUseExisting:302, ES6AddImportExecutor (com.intellij.lang.ecmascript6.actions)
executeImpl:46, ImportES6ModuleFix (com.intellij.lang.javascript.modules)
invokeAction:104, ImportCommonJSModuleFix (com.intellij.lang.javascript.modules)
insertJSImport:730, ES6ImportPsiUtil (com.intellij.lang.ecmascript6.psi.impl)
insertJSImport:717, ES6ImportPsiUtil (com.intellij.lang.ecmascript6.psi.impl)
insertJSImport:680, ES6ImportPsiUtil (com.intellij.lang.ecmascript6.psi.impl)
insertJSImport:672, ES6ImportPsiUtil (com.intellij.lang.ecmascript6.psi.impl)
......
insertLookupItem:519, JSImportCompletionUtil (com.intellij.lang.javascript.completion)
importForElement:451, JSImportCompletionUtil (com.intellij.lang.javascript.completion)
access$100:63, JSImportCompletionUtil (com.intellij.lang.javascript.completion)
handleInsert:543, JSImportCompletionUtil$ImportInsertHandler (com.intellij.lang.javascript.completion)
....
lambda$insertItem$15:688, CodeCompletionHandlerBase (com.intellij.codeInsight.completion)
...
doInsertItem:587, CodeCompletionHandlerBase (com.intellij.codeInsight.completion)
insertItemHonorBlockSelection:547, CodeCompletionHandlerBase (com.intellij.codeInsight.completion)
lookupItemSelected:493, CodeCompletionHandlerBase (com.intellij.codeInsight.completion)
...
```

**Comment by bbuhler** [comment]
It's the same for the quick action "insert import":

![Screen record from 2020-10-30 14 54 26](https://user-images.githubusercontent.com/2802675/98092547-14019b80-1e87-11eb-962c-85db9f94d052.gif)

**Comment by Treverix** [comment]
This works for me (now) unless I missed something obvious

![svelte-import](https://user-images.githubusercontent.com/1685275/122040740-7a18ae80-cdd8-11eb-9bef-e51590908b84.gif)

**Comment by bbuhler** [comment]
@Treverix it does not work outside of the script tag.

**Comment by Treverix** [comment]
@bbuhler ok, I see - I just noticed that it works inside the script tag and also on a blank file now - it does not put the `import` inside the curly brackets (anymore) but yes, if there is script element, it does not add it to it, the import is put outside.

**Comment by unlocomqx** [comment]
Thank you @tomblachut for your work on the plugin and the platform!

**Comment by tomblachut** [comment]
It's a pleasure 😊
