### ISSUE TITLE
Support await catch shorthand tag

### ISSUE THREAD

**Issue by tomblachut** [tomblachut/svelte-intellij#135]
Added in Svelte 3.21.0

**Comment by r00t3g** [comment]
@tomblachut I may be missing something, yet currently it seems to be working properly:
![image](https://user-images.githubusercontent.com/579779/89727278-b72f4a00-da2b-11ea-92e9-c755bea4f743.png)

**Comment by tomblachut** [comment]
@r00t3g I meant tag, not block ;) let me clarify the title more.

```
{#await promise catch error}
  {error.message}
  <Auth>
{/await}
```
