### ISSUE TITLE
Long function calls inside Svelte expressions aren't wrapped

### ISSUE THREAD

**Issue by ghost** [tomblachut/svelte-intellij#140]

**Comment by tomblachut** [comment]
Please update to 0.13.0

**Comment by LaniJW** [comment]
Update isn't available in the Plugin page of PhpStorm and even after trying to install 0.13.0 with the zip PhpStorm rejects it with "Plugin 'Svelte' is incompatible with this installation".

**Comment by tomblachut** [comment]
I guess you have version 2019. Sorry about that but I don't have capacity to maintain compatibility with older products. This is an evening side project

**Comment by LaniJW** [comment]
I updated now but it still doesn't seem to break long lines. Do I have to do something other than execute the action "Reformat Code"?

**Comment by tomblachut** [comment]
It should work, maybe there is a bug :) Please paste the code you want to format.

**Comment by LaniJW** [comment]
Of course. Here you go:

```<table class="uk-table uk-table-small uk-table-divider">
	<tbody>
		<tr>
			<td>Stars</td>
			<td>{stats.player.achievements.bedwars_level}</td>
		</tr>
		<tr>
			<td>Wins</td>
			<td>{stats.player.achievements.bedwars_wins}</td>
		</tr>
		<tr>
			<td>Games Played</td>
			<td>{stats.player.stats.Bedwars.games_played_bedwars_1}</td>
		</tr>
		<tr>
			<td>Winstreak</td>
			<td>{Math.max(stats.player.stats.Bedwars.eight_one_winstreak, stats.player.stats.Bedwars.eight_two_winstreak, stats.player.stats.Bedwars.eight_two_ultimate_winstreak, stats.player.stats.Bedwars.four_three_winstreak, stats.player.stats.Bedwars.four_four_winstreak)}</td>
		</tr>
		<tr>
			<td>Games Played</td>
			<td>{stats.player.stats.Bedwars.games_played_bedwars_1}</td>
		</tr>
	</tbody>
</table>
```

**Comment by tomblachut** [comment]
![image](https://user-images.githubusercontent.com/615013/90310423-79319a80-def1-11ea-8904-d161e96e1d94.png)
Well this is certainly weird.

For now you'll need to add newlines yourself or use Prettier. And to be honest this should be refactored to dedicated variable/function/component

**Comment by tomblachut** [comment]
Migrated to [WEB-61846](https://youtrack.jetbrains.com/issue/WEB-61846) Svelte: format long markup expressions
