### ISSUE TITLE
Typescript import type incorrectly marked as broken

### ISSUE THREAD

**Issue by y-y-yoshi** [tomblachut/svelte-intellij#141]
Hi,

when using the typescript type import in the script tag in a svelte file like this:
```
<script  lang="typescript">
  import type Foo from "./foo";
 ....
</script>
```
the import is marked as broken, although serving the app works fine.

**Comment by tomblachut** [comment]
TS it not yet supported.

**Comment by tomblachut** [comment]
Works in newest release!
