### ISSUE TITLE
Performance issue indexing large monorepo project

### ISSUE THREAD

**Issue by btakita** [tomblachut/svelte-intellij#157]
I vaguely remember that after upgrading to 0.13.0, a large monorepo project using yarn + lerna took > 1 minute to load. After switching to pnpm + @microsoft/rush, Webstorm hangs & does not load the project. `kill -9 $WEBSTORM_PID` is needed to kill the webstorm process.

Please see https://youtrack.jetbrains.com/issue/WEB-47460

**Comment by tomblachut** [comment]
Would be nice to get some repro project, hard to tell anything without that.
