### ISSUE TITLE
Comment with Line/Block Comment actions not working

### ISSUE THREAD

**Issue by russelgal** [tomblachut/svelte-intellij#16]
![image](https://user-images.githubusercontent.com/3201077/57794038-2c926900-775c-11e9-83f0-208a2f1131b9.png)
![screencast 2019-05-15 21-56-23](https://user-images.githubusercontent.com/3201077/57794143-6e231400-775c-11e9-9ca5-6687aea48df4.gif)

**Comment by russelgal** [comment]
my bad, plugin somehow not updated

**Comment by tomblachut** [comment]
😅
