### ISSUE TITLE
Compatibility with 2020.3 (EAP)

### ISSUE THREAD

**Issue by tomblachut** [tomblachut/svelte-intellij#162]
Plugin is incompatible for now. I'm aware of changes in the platform and in the future there will be new version that works in 2020.3.

**Comment by vjandrea** [comment]
@tomblachut if you need a beta tester let me know!

**Comment by piotrtomiak** [comment]
@tomblachut FYI, I am working on supporting lexer changes for 203. I should have a PR ready by the end of the week.

**Comment by tomblachut** [comment]
@piotrtomiak thank you!

**Comment by tomblachut** [comment]
[Branch 203](https://github.com/tomblachut/svelte-intellij/tree/203) contains code compatible with 2020.3 for now.

**Svelte 0.15.2.203** should appear in IDEs tomorrow
https://plugins.jetbrains.com/plugin/12375-svelte/versions/stable/102349

**Comment by anstarovoyt** [comment]
@tomblachut it would be great to release a new 16.* version for 2020.3 because without the version update 2020.2 + 0.16 -> 2020.3 will show that there is no compatible version (because auto-update for plugins supports only versions upgrade, not downgrade)

**Comment by tomblachut** [comment]
Right, I'll release 0.16.0.203 as soon as GitHub Action updates master, this flow is manual for now

**Comment by tomblachut** [comment]
I should've put that into release description 😅

**Comment by tomblachut** [comment]
Done, **Svelte 0.16.0.203** has been submitted to the Marketplace
https://plugins.jetbrains.com/plugin/12375-svelte/versions/stable/103776
