### ISSUE TITLE
Svelte's transitions are not recongnized as used

### ISSUE THREAD

**Issue by r00t3g** [tomblachut/svelte-intellij#164]
Referencing a transition function from 'svelte/transition' in HTML code does not mark the import as used. Occurs in 0.14 as well.

![image](https://user-images.githubusercontent.com/579779/96093984-79401d80-0ed5-11eb-9e13-a1f2b85d63c3.png)

**Comment by tomblachut** [comment]
Hey, that's because references in directives are not yet recognized. Last piece of core Svelte semantics missing.

Please refer to #11
