### ISSUE TITLE
svelte:component is not recognized inside a block

### ISSUE THREAD

**Issue by shirotech** [tomblachut/svelte-intellij#169]
If we put a ```<svelte:component/>``` element inside an if or any other block, it doesn't seem to be recognized.
<img width="604" alt="Screen Shot 2020-10-25 at 2 29 37 pm" src="https://user-images.githubusercontent.com/1149825/97098246-d191cf00-16ce-11eb-9ffa-6c1e63d789f7.png">
On top-level, it works fine.
<img width="390" alt="Screen Shot 2020-10-25 at 2 29 54 pm" src="https://user-images.githubusercontent.com/1149825/97098252-e0788180-16ce-11eb-9b24-56d9a04c4aa5.png">

**Comment by tomblachut** [comment]
Thanks for reporting

**Comment by tomblachut** [comment]
This is regression from parser rewrite in v0.13 afaiu

**Comment by tomblachut** [comment]
Will release today/tomorrow in v0.15.2
