### ISSUE TITLE
Support for lang="scss"

### ISSUE THREAD

**Issue by sorin-coza** [tomblachut/svelte-intellij#17]
I wasted an hour until I realized that this plugin works fine with `<style type="text/scss">`.

I was using `<style lang="scss">`, because that's what the [VueJS plugin](https://github.com/JetBrains/intellij-plugins/tree/master/vuejs) uses, and that's what I used on Vue apps. Also the [Svelte preprocess package](https://www.npmjs.com/package/svelte-preprocess) is documenting `lang="scss"`, so I thought that was the right way to do it.

So, it would be great to add support for `lang="scss"`, since Vue developers are already used to that.

Thanks for your great plugin!

**Comment by tomblachut** [comment]
Definitely. Thanks for raising. 

I'll note that I don't see how Pug can be supported in the near future, anyway CSS flavors should be doable.

**Comment by AleksandrSl** [comment]
Seems like I've got this to work using hacks from Vue plugin, will try to comprehend these hacks and make PR
