### ISSUE TITLE
Did anyone manage to set breakpoints/debug .svelte files?

### ISSUE THREAD

**Issue by JakubKoralewski** [tomblachut/svelte-intellij#174]
I found only [this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360006858160-How-can-I-enable-setting-breakpoints-to-files-that-are-not-js-svelte-for-example-), but if you add `*.svelte` as a Javascript file then you lose all the features that this plugin provides...

**Comment by anstarovoyt** [comment]
@tomblachut we need something like this: https://github.com/anstarovoyt/intellij-riot.js/commit/ef86696926615e1fbd1a8ba38c85bf177f035876

**Comment by tomblachut** [comment]
@anstarovoyt that would be nice, thanks! 
I'm focusing on #173 right now, would like to finish it before 2020.3 because it's the last big part of Svelte missing

**Comment by tomblachut** [comment]
Will be released as part of 0.16.0
