### ISSUE TITLE
Unresolved variable error in reactive destructuring assignments

### ISSUE THREAD

**Issue by broad-well** [tomblachut/svelte-intellij#181]
To reproduce this issue, try the following:

```svelte
<script>
  $: [a, b, c] = [1, 2, 3];
</script>
```

This is a valid segment that is semantically similar to `let [a, b, c] = [1, 2, 3]`. It compiles and behaves as expected, but the plugin claims that `a`, `b`, and `c` are unresolved variables or types.

**Comment by tomblachut** [comment]
I spent some time trying to fix this, but unfortunately it will require lots of engineering hours as far as I understand

**Comment by anstarovoyt** [comment]
@tomblachut I will take a look, maybe we need some magic knowledge there :)

**Comment by hiluw** [comment]
Perhaps this is related to #249

**Comment by tomblachut** [comment]
@hiluw not really, destructuring is handled separately from basic variables

**Comment by NickAlvesX** [comment]
Same thing for `$: ({ isPaused }: StoreData = $store);`

**Comment by tomblachut** [comment]
Migrated to [WEB-53209](https://youtrack.jetbrains.com/issue/WEB-53209) Svelte: Unresolved variable false-negative for destructured reactive declaration references
