### ISSUE TITLE
2020.3 store autosubscription regression

### ISSUE THREAD

**Issue by shirotech** [tomblachut/svelte-intellij#184]
unresolved when prefixing $ for a store in script block, but it works fine in HTML markup.

**Comment by tomblachut** [comment]
![image](https://user-images.githubusercontent.com/615013/100716259-be9ea880-33b8-11eb-9077-3422b2377907.png)
seems to be working, can you create repro project?

**Comment by MetaHegemon** [comment]
Same problem. Code work fine.
![image](https://user-images.githubusercontent.com/7349599/100775786-8a150600-3425-11eb-9e0e-b5b26d0da78d.png)

**Comment by bsl-zcs** [comment]
![image](https://user-images.githubusercontent.com/3049410/100845209-11ef2480-34a7-11eb-8ce4-7dc186f51adb.png)

same behavior in 2020.3 with both 0.16.0.203 and 0.15.0.203

**Comment by tomblachut** [comment]
Thanks for screenshots. It seems to be broken only in JS script tags for some reason, TS works fine as far as I see.

**Comment by tomblachut** [comment]
Fixed in https://github.com/tomblachut/svelte-intellij/commit/eb679b6618a500f004444c2e2aee19e9ae8d7e51, will be included in next release
