### ISSUE TITLE
Remove browsers floating toolbar

### ISSUE THREAD

**Issue by PierBover** [tomblachut/svelte-intellij#185]
For some reason WebStorm insists on showing these browser suggestions on `.svelte` files:

![image](https://user-images.githubusercontent.com/226483/101124868-7b615700-35bd-11eb-875a-88ca3f210fa5.png)

I imagine this happens because of the HTML content in Svelte components.

Is there a way to disable this for `.svelte` files from the plugin?

**Comment by tomblachut** [comment]
It's specifically because .svelte file is a subtype of .html file type so you get standard inspections etc.

Last time I checked it's not possible to disable from plugin side but surely it can be changed in the future

**Comment by PierBover** [comment]
Thanks @tomblachut .

I guess it's best to close this for now.

**Comment by tomblachut** [comment]
@PierBover this is actually valid feature request so I'd leave it as open so people can vote etc.

Related issue: https://youtrack.jetbrains.com/issue/WEB-48558

**Comment by tomblachut** [comment]
Browsers floating toolbar doesn't show up in `.svelte` files starting from 2021.1.
