### ISSUE TITLE
Quotes in curly braces break HTML Tag

### ISSUE THREAD

**Issue by Maggi64** [tomblachut/svelte-intellij#194]
I encountered this when using same quotes in the curly braces as in the html tags.

![image](https://user-images.githubusercontent.com/20517052/102222605-ed05a300-3ee3-11eb-9df8-162844bd1a19.png)

---

![image](https://user-images.githubusercontent.com/20517052/102222741-1c1c1480-3ee4-11eb-9d1a-02f3b19a43dc.png)

---

![image](https://user-images.githubusercontent.com/20517052/102222885-4d94e000-3ee4-11eb-8ec5-f0c469b4b477.png)

I can provide additional code and examples if needed.
Keep up the good work and have nice holidays 🎄

**Comment by tomblachut** [comment]
@Maggi64 thanks, you too 🎄 

thanks for reporting
https://svelte.dev/repl/8ed50e6b0c80438b8eecbbb78bd92c3f?version=3.31.0

**Comment by tomblachut** [comment]
Migrated to [WEB-61824](https://youtrack.jetbrains.com/issue/WEB-61824) Svelte: fix parser issues
