### ISSUE TITLE
Inline style variables error

### ISSUE THREAD

**Issue by Maggi64** [tomblachut/svelte-intellij#195]
Hi again,
setting inline style variables seems to throw an error, but it shouldn't.

![image](https://user-images.githubusercontent.com/20517052/102614764-1b2df180-4135-11eb-9c8a-1b9660fb4104.png)

Stay woke 💯 

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

**Comment by tomblachut** [comment]
Is this 2020.3?

**Comment by Maggi64** [comment]
yes

**Comment by tomblachut** [comment]
It's a regression in 2020.3 connected to #80
