### ISSUE TITLE
Typescript checks ignoring undefined

### ISSUE THREAD

**Issue by Coobaha** [tomblachut/svelte-intellij#197]
Hi @tomblachut ! Thanks for this awesome plugin!
I've noticed that ts type checking is buggy with this snippet
```html
<script lang="typescript">
  type Ctx = {
    ddd: void | string;
    dddd: undefined | string;
  };
  let test: string;
  export let ctx: Ctx;
  if (ctx) {
    test = ctx.dddd;
    test = ctx.ddd;
  }

</script>
```

![image](https://user-images.githubusercontent.com/2446638/103341387-7c3bba80-4a8f-11eb-90b7-0f627b97afbe.png)

Vscode

![image](https://user-images.githubusercontent.com/2446638/103341469-b6a55780-4a8f-11eb-93ba-7f57ba5b8274.png)

**Comment by tomblachut** [comment]
I don't understand, why do you think it's buggy?

**Comment by Coobaha** [comment]
For some reason it narrows down the type without `undefined`  (and i believe nulls too)

**Comment by tomblachut** [comment]
Ah I didn't spot two errors, thanks for clarification

**Comment by tomblachut** [comment]
Verified to work in [v0.21.0](https://github.com/tomblachut/svelte-intellij/releases/tag/v0.21.0)

![image](https://user-images.githubusercontent.com/615013/126820990-5a3fec01-1df4-4905-bdb0-de329990902f.png)
