### ISSUE TITLE
Quotes in regex breaks file

### ISSUE THREAD

**Issue by Maggi64** [tomblachut/svelte-intellij#199]
Hi again, thx for the latest update spotted another bug.

Something like this breaks the file: `class:materials={/"/.test()}`

---
![image](https://user-images.githubusercontent.com/20517052/105911413-730c2200-602a-11eb-841d-737bf9a6ed84.png)

**Comment by tomblachut** [comment]
Migrated to [WEB-61824](https://youtrack.jetbrains.com/issue/WEB-61824) Svelte: fix parser issues
