### ISSUE TITLE
<style>: nested rules break parsing/inspection

### ISSUE THREAD

**Issue by Mikk36** [tomblachut/svelte-intellij#208]
![image](https://user-images.githubusercontent.com/5886412/111284862-37183500-8649-11eb-9cd8-b2331576f026.png)

Using them currently with Windi CSS

**Comment by tomblachut** [comment]
The problem is nested rules in plain CSS, right?

**Comment by Mikk36** [comment]
Looks like everything with nested rules breaks.
![image](https://user-images.githubusercontent.com/5886412/111293720-3cc64880-8652-11eb-83c8-02c68d9b1044.png)

**Comment by tomblachut** [comment]
Yes, because that's not CSS

**Comment by tomblachut** [comment]
Enabling PostCSS would resolve that problem I think

**Comment by Mikk36** [comment]
PostCSS is already enabled in the project and the code compiles, it's just the editor, that's unhappy.
Do I have to enable PostCSS somewhere in the editor/plugin settings?

**Comment by tomblachut** [comment]
Sorry I'm not sure, I'll investigate more later

**Comment by maiksch** [comment]
I have the same problem and was able to solve it by adding lang="scss" to the <style> tag. Unfortunately, there seems to be the same problem with <script lang="ts">, which otherwise does not highlight syntax or show typescript imports correctly. 

Apparently the language is not automatically pulled from the svelte config where the defaults are configured.

**Comment by tomblachut** [comment]
> Apparently the language is not automatically pulled from the svelte config where the defaults are configured.

That's correct

**Comment by Mikk36** [comment]
Looks like this issue can be closed.
Proper markup looks like this:
```PostCSS
<style lang="scss">
  div {
    flex-basis: 250px;

    @screen sm {
      flex-basis: 0;
    }
  }
</style>```

**Comment by ethan-jones-vizio** [comment]
Using PostCSS + postcss-nested shows errors even with `lang="postcss"` specified
![PostCSS Svelte IntelliJ](https://i.imgur.com/i0vmWNF.png)
