### ISSUE TITLE
SvelteKit

### ISSUE THREAD

**Issue by tomblachut** [tomblachut/svelte-intellij#209]
[SvelteKit](https://kit.svelte.dev/) went into public beta. This issue is meant to track improvements on intellij plugin side.
 
- [x] `sveltekit:prefetch`, `sveltekit:noscroll`, `rel=external` – completions, do not highlight as not allowed
- [ ] `load` function 
    - [x] mark as implicitly used
    - [ ] completions
    - [ ] (?) suggest and validate prop types defined on component and returned from load function
- [ ] `hydrate`, `prerender`, `router`, `ssr` variables
    - [x] mark as implicitly used
    - [ ] completions
- [ ] hooks – mark as implicitly used (`handle`, `getSession`, `serverFetch`)
- [ ] api functions – mark as implicitly used (`get`, `del`, etc)
- [ ] project generator based on `create-svelte`
- [ ] mark `.svelte` subdirectories as library roots or excluded
- [x] file references to `static` directory – suppress inspection ~or contribute references~
- [ ] [Events on window](https://kit.svelte.dev/docs#events)
- [x] Correct highlighting of `$app/*` paths

Update: 
* some improvements are available in [v0.20.0](https://github.com/tomblachut/svelte-intellij/releases/tag/v0.20.0)
* `$app/*` is fixed in [v0.21.0](https://github.com/tomblachut/svelte-intellij/releases/tag/v0.21.0)

**Comment by wiesson** [comment]
Typescript path alias / resolve does not work for me as well. It could also be a vite issue, but I'm not sure

**Comment by eXodes** [comment]
I added preprocess defaults for css and script config in `svelte.config.js`, `postcss` for css works but `typescript` for script does not. Is this because the Svelte config is new?

**Comment by miosenpai** [comment]
Is addressing import errors on modules like `$app/store` on the agenda as well? It makes using SvelteKit in IntelliJ kind of frustrating sometimes.
![image](https://user-images.githubusercontent.com/5713101/125819934-b576c0e5-1b6c-4da9-a26b-8639ccafbfed.png)

**Comment by tomblachut** [comment]
@miosenpai yes, sure. It's missing in checklist and I'll amend that.

**Comment by tomblachut** [comment]
@miosenpai  Workaround is to copy `ambient-modules.d.ts` (you can find it with `Shift+Shift` popup) and paste it into `src/global.d.ts`

**Comment by jjrgen** [comment]
Private components are not visible for import – https://kit.svelte.dev/docs#routing-private-modules

![image](https://user-images.githubusercontent.com/54930934/133376767-acf8daf4-387c-4c2b-96fa-4a2e5a8b81f6.png)
![image](https://user-images.githubusercontent.com/54930934/133376901-b802ec87-ba63-49f5-96b6-b04f0b8558a6.png)

I would expect `<PrivateComponent />` to give me an auto import like `import PrivateComponent from './_PrivateComponent'`

**Comment by FlymeDllVa** [comment]
@tomblachut, hi!

Are there any plans to develop the plugin? In the current version to use it with SvelteKit, very difficult, almost nothing is indexed and it seems the only option is to use VSCode :(

**Comment by tomblachut** [comment]
There was lots of changes to SvelteKit since the list was written, most things work in 2023.2 thanks to [WEB-58397](https://youtrack.jetbrains.com/issue/WEB-58397) use the svelte language server.

missing bits:
* [WEB-61821](https://youtrack.jetbrains.com/issue/WEB-61821) SvelteKit: mark load, actions etc as used 
* [WEB-61610](https://youtrack.jetbrains.com/issue/WEB-61610) use typescript-svelte-plugin.

Please open any additional issues on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=WEB), thanks!
