### ISSUE TITLE
{:else} & {/if} formatting outdented

### ISSUE THREAD

**Issue by btakita** [tomblachut/svelte-intellij#21]
On reformat, `{:else}` & `{/if}` get outdented.

![svelte-plugin-formatting-issue](https://user-images.githubusercontent.com/3664/58416255-f0f67980-804e-11e9-88a3-4100ad2a200c.png)

**Comment by tomblachut** [comment]
Weird. Could you paste this snippet as text?

**Comment by rwwagner90** [comment]
Not sure if this is the same issue I am seeing, but when I autoformat, my svelte tags get indented too far, rather than respecting the html settings.

```html
<svelte:head>
  <title>{title}</title>

    {#each meta as item}
      <meta name={item.name} content={item.content}/>
    {/each}

    {#each link as item}
      <link rel={item.rel} href={item.href}/>
    {/each}
</svelte:head>
```

Note that title is correctly indented 2 spaces,  and the `each` blocks get indented 4.

**Comment by tomblachut** [comment]
@rwwagner90 I've pasted your code into empty file in version 0.8.0 and it indents properly. Let me know if it still happens for you
