### ISSUE TITLE
Expressions inside title tag are parsed as plain text

### ISSUE THREAD

**Issue by r00t3g** [tomblachut/svelte-intellij#210]
Therefore, as the variable is treated as unused, its import gets removed when running 'Reformat code' with 'Optimize imports' option. Apart from all other problems like not found usages etc.

![image](https://user-images.githubusercontent.com/579779/113060274-160f2280-91b9-11eb-930b-12ab747f6d29.png)

**Comment by tomblachut** [comment]
Hi. It should work in latest release. What version of plugin and IDE are you running? Also, what "SUBJ" means? Thanks

**Comment by r00t3g** [comment]
@tomblachut IDE is IntelliJ Idea 2020.3.3, plugin - 0.18.0.203
Removed the SUBJ, sorry :)

It looks that it breaks only when the variable usage follows some text and works OK in any other case:
![image](https://user-images.githubusercontent.com/579779/113748654-7221fb80-9711-11eb-9f11-6db5bc3f8a02.png)

Cmd/Ctrl+Click navigation also seems not to work the variable.

**Comment by tomblachut** [comment]
Oh ok, I've reproduced the problem. Thanks for reporting.

This is a bug in parser.  Happens specifically inside title and similar because according to [MDN only text is allowed inside](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title)

**Comment by tomblachut** [comment]
This is actually a regression 😔 https://youtrack.jetbrains.com/issue/WEB-41745

**Comment by tomblachut** [comment]
Migrated to [WEB-61785](https://youtrack.jetbrains.com/issue/WEB-61785) Svelte: properly parse title tag content
