### ISSUE TITLE
Unresolved functions

### ISSUE THREAD

**Issue by unlocomqx** [tomblachut/svelte-intellij#215]
Some functions are not resolved when using lang=ts

<img width="466" alt="2021-04-25 at 4 07 PM" src="https://user-images.githubusercontent.com/793712/115998724-8b1b1f80-a5e0-11eb-8f4b-4d8dc458d5d1.png">

I used the svelte template to reproduce

```bash
npx degit sveltejs/template svelte-app
cd svelte-app
node scripts/setupTypeScript.js
```

I don't know if it's caused by my IDE settings or by the extension
The JS Language level is set to ES6+ if that's relevant to this

**Comment by r00t3g** [comment]
It might be related to misconfiguration in tsconfig - target or lib sections, not the plugin

**Comment by unlocomqx** [comment]
After adding "es2017" to tsconfig, I couldn't reproduce it on the svelte template. It still occurs in my main project though  but I guess it doesn't come from the plugin itself.

**Comment by unlocomqx** [comment]
I was able to reproduce on the svelte template. The issue doesn't occur on App.svelte but on other components only (that are not imported by main.ts)
Can you check if you can repro?

App.svelte
<img width="334" alt="app" src="https://user-images.githubusercontent.com/793712/119228202-d9510f00-bb09-11eb-9db3-25d1967eea51.png">

Comp.svelte
<img width="585" alt="comp" src="https://user-images.githubusercontent.com/793712/119228208-df46f000-bb09-11eb-9772-4643693c9182.png">

When Comp.svelte is imported in main.ts the issue goes away

For info, `String.includes` is part of `ES2015` and `Array.includes` is part of `ES2016` according to intellij declaration files at least

**Comment by tomblachut** [comment]
Hey @unlocomqx thanks for reporting, I was able to reproduce. I'll close this in favor of https://youtrack.jetbrains.com/issue/WEB-51050

**Comment by unlocomqx** [comment]
Sorry for double reporting, I thought it must be an issue with webstorm itself not the plugin but the webstorm team member scoped it to the plugin anyway! Cheers.

**Comment by tomblachut** [comment]
No problem :)
