### ISSUE TITLE
Problem on attributes with { }

### ISSUE THREAD

**Issue by vendaagil** [tomblachut/svelte-intellij#217]
Hello, My PhpStorm error on attributes when use { }

![image](https://user-images.githubusercontent.com/55722495/116489265-f841e580-a86a-11eb-95d6-92e10cb27c08.png)
![image](https://user-images.githubusercontent.com/55722495/116489272-ff68f380-a86a-11eb-9ad0-47e9d2e7ab16.png)

**Comment by tomblachut** [comment]
Hi! What version of IDE and plugin are you using?

**Comment by vendaagil** [comment]
> 
> 
> Hi! What version of IDE and plugin are you using?

Hello,

![image](https://user-images.githubusercontent.com/55722495/116584724-06851580-a8ee-11eb-81e7-dbc190b8c673.png)
![image](https://user-images.githubusercontent.com/55722495/116584834-23214d80-a8ee-11eb-9e8d-fff9334b1f6c.png)

**Comment by tomblachut** [comment]
Those are very old versions, especially of plugin. Please try with latest ones, it should work there.

**Comment by vendaagil** [comment]
How to update plugin?

**Comment by vendaagil** [comment]
![image](https://user-images.githubusercontent.com/55722495/116597560-215e8680-a8fc-11eb-94e3-f2961878870b.png)
