### ISSUE TITLE
Change tracking sometimes not working properly

### ISSUE THREAD

**Issue by brud** [tomblachut/svelte-intellij#219]
Hi @tomblachut, first of all thanks a lot for a great job!

I have a question (or probably I find a bug): sometime if I make changes in *.svelte file and open browser - changes are untracked. But if after that I open IDE and click on terminal tab - hot reload starts to work.

Is it plugin error, or IDE? (I tried plugin on last version Rider and WebStorm)

**Comment by tomblachut** [comment]
Hi @brud! There isn't anything special in the plugin specific to hot reload. You might try to check your settings as described here https://www.jetbrains.com/help/webstorm/working-with-source-code.html#auto_save

**Comment by tomblachut** [comment]
Closing as inactive
