### ISSUE TITLE
props without quotes breaks formatting and highlighting

### ISSUE THREAD

**Issue by russelgal** [tomblachut/svelte-intellij#22]
![image](https://user-images.githubusercontent.com/3201077/58451803-79981700-812e-11e9-8c6c-2b30b7ce941c.png)
![image](https://user-images.githubusercontent.com/3201077/58451899-caa80b00-812e-11e9-8f30-e6d242ce1bc1.png)
```
<form on:submit={e => User.login(e, router)}>
<label>
	email
	<input name="email" type="email" value="user@example.com"/>
</label>
<label>
	password
	<input name="password" type="password" value="secretPassword"/>
</label>
<input type="submit" value="Login"/>
</form>
```

**Comment by nightwolfz** [comment]
![image](https://user-images.githubusercontent.com/805022/64130729-8464e680-cdc4-11e9-9765-d36bce553171.png)

**Comment by tomblachut** [comment]
@nightwolfz  PRs are welcome...

For the time being please wrap expressions in quotes
