### ISSUE TITLE
Component props types suggestion

### ISSUE THREAD

**Issue by mgrisole** [tomblachut/svelte-intellij#220]
Hi, thanks for this really nice plugin !

Would it be possible to add type suggestion for component props ?

![image](https://user-images.githubusercontent.com/33571141/117066363-a24fc080-acf6-11eb-9818-2e6818c1cc1e.png)

**Comment by r00t3g** [comment]
I think there is already such request: https://github.com/tomblachut/svelte-intellij/issues/207

**Comment by mgrisole** [comment]
Not entirely sure if #207 fix would also fix this one.

**Comment by tomblachut** [comment]
Migrating to YouTrack, should be included in [WEB-58397](https://youtrack.jetbrains.com/issue/WEB-58397) use the svelte language server, and others. Otherwise please create another one.
