### ISSUE TITLE
Build JS class type for Svelte component seen from other files

### ISSUE THREAD

**Issue by ghost** [tomblachut/svelte-intellij#223]
![image](https://user-images.githubusercontent.com/52130524/121469013-0af82000-c9bc-11eb-8bc5-df6710136bfa.png)

**Comment by jiby-gh** [comment]
@tomblachut first of all thanks for the work on the plugin, most of the things work very well. I just noticed that seemingly functions exports from components are not handled.

**Comment by r00t3g** [comment]
Confirming this issue - it's quite old though. The same problem also applies to component instances outside of Svelte context:
![image](https://user-images.githubusercontent.com/579779/121509055-ecf7e300-c9ee-11eb-924a-78a0a5bb1008.png)

**Comment by tomblachut** [comment]
This is actually manifestation of not implemented type evaluation of Svelte files

**Comment by Treverix** [comment]
I ran into a similiar problem with `context="module"`. Their exports are also not visible although it compiles and works fine

*Provider.svelte*
```svelte
<script context='module' lang='ts'>
  export const foo:string = 'bar';
</script>
```

*Main.svelte* (with workaround)
```svelte
<script lang='ts'>
  import {foo as _foo} from './Provider.svelte';  // foo is in red - not found
  const foo = _foo as string;  // Workaround to get the typing back
</script>
```

**Comment by tomblachut** [comment]
@jiby-gh It will be handled. There's no timeframe right now, sorry.

As a side note, personally, I struggle to find real life use case for such pattern.

**Comment by r00t3g** [comment]
@tomblachut, Apart from that is is stated supported in the Svelte API docs, for example, in one of our projects it is really a useful feature as we are switching a large codebase from native-JS custom components to Svelte and compoenent methods are required to provide integration bridges between the legacy code and the new component. It is also quite usable as a prop accessor when you need to get a single actual internal prop value from the component into external module and you don't want to enable compiler's `accessors: true` or use stores for some reason.

**Comment by tomblachut** [comment]
@r00t3g I see, thanks for the example. It's quite advanced.

**Comment by tomblachut** [comment]
Oops I've messed the rename

**Comment by lxhom** [comment]
I've found another workaround that's pretty simple and automatically import types:

###### Control.svelte
```svelte
<script lang="ts" context="module">
	import App, * as _App from "./App.svelte"
	let { gui, Button } = _App;
    ...
</script>
<App />
```
###### App.svelte
```svelte
<script lang="ts" context="module">
	...
	let gui = new GUIClass();
	enum Button { Encrypt, Decrypt, Help }
	...
	export { gui, Button }
</script>
...
```
Works like a charm in WebStorm.
![2021-11-15-104038_746x328_scrot](https://user-images.githubusercontent.com/73352734/141759374-79b0cdbb-4a01-451d-8c1f-728f73f4c871.png)

**Comment by tomblachut** [comment]
Migrating to [WEB-61825](https://youtrack.jetbrains.com/issue/WEB-61825) Svelte: Build JS class type for Svelte component seen from other files

but actually should be mostly covered by [WEB-58397](https://youtrack.jetbrains.com/issue/WEB-58397) use the svelte language server
