### ISSUE TITLE
Different tooltips for same variable (typescript)

### ISSUE THREAD

**Issue by Treverix** [tomblachut/svelte-intellij#227]
I noticed that the plugin sometimes shows different tooltips for the same variable. The tooltip on the first image is probably the correct one.

![image](https://user-images.githubusercontent.com/1685275/122002560-2e530e80-cdb2-11eb-9dbf-01a3e0c0216c.png)

![image](https://user-images.githubusercontent.com/1685275/122002599-3f038480-cdb2-11eb-80e7-9454ec940ed2.png)

**Comment by tomblachut** [comment]
Hi! Does the same problem appear in JS file?

**Comment by Treverix** [comment]
No... only on typescript mode... on js, it's all good :)

here's a simple example:

```svelte
<script lang="ts">
    import {writable} from 'svelte/store'
    const w = writable(false);
    const unsubscribe = w.subscribe((newValue) => console.log('changed to ' + newValue))
    unsubscribe();
</script>

<div></div>
```

![image](https://user-images.githubusercontent.com/1685275/122025840-fce63d00-cdc9-11eb-8e34-074b2773f536.png)

![image](https://user-images.githubusercontent.com/1685275/122025891-096a9580-cdca-11eb-9165-6ead0cf22715.png)

**Comment by tomblachut** [comment]
I meant outside of Svelte, can you observe same problem in JS file vs TS file?

**Comment by Treverix** [comment]
Ah sorry - got it :) Now it looks like a bug in the IDEA typescript plugin - it happens on normal typescript files also.

![image](https://user-images.githubusercontent.com/1685275/122027407-6286f900-cdcb-11eb-9c98-68afd5a34524.png)

I file it on their youtrack.

**Comment by tomblachut** [comment]
Ok, thanks for clarification!

**Comment by Treverix** [comment]
https://youtrack.jetbrains.com/issue/WEB-51306
