### ISSUE TITLE
Add import statement as 'import type' for types and interfaces (typescript)

### ISSUE THREAD

**Issue by Treverix** [tomblachut/svelte-intellij#228]
We can let intellij add a missing import and that also works on svelte source files with `lang="ts"`.

![image](https://user-images.githubusercontent.com/1685275/122003517-7de60a00-cdb3-11eb-994c-a889a4603e1f.png)

The only trouble is: svelte requires that all types and interfaces to be imported as type

```typescript
import type {SuiteSelectorEvents} from "./types";
```

while the current plugin adds it like that:

```typescript
import {SuiteSelectorEvents} from "./types";
```

That is probably the default behavior of IDEA but it would be great if the plugin could add the import as `import type` here because otherwise we observe (pretty misleading) compile errors when we miss to fix it immediately.

**Comment by SelcukKayahan** [comment]
Same here. Already tried this among others: https://youtrack.jetbrains.com/issue/WEB-43269

**Comment by tomblachut** [comment]
Will be supported in 2021.2 as part of https://youtrack.jetbrains.com/issue/WEB-50851
