### ISSUE TITLE
Misses to detect syntax error on some imports

### ISSUE THREAD

**Issue by Treverix** [tomblachut/svelte-intellij#229]
Me again ;) I was just puzzled that a svelte file that 'looked' good didn't compile. I missed one single quotation mark on an import and both me and the svelte plugin didn't see that.

Works on typescript files and it is indepedent of the svelte language level (happens on js and ts). 

It only happens when we import a full script, not just from a script.

And thanks again for the great plugin!

![image](https://user-images.githubusercontent.com/1685275/122037844-48521880-cdd5-11eb-8771-737011730d60.png)

**Comment by tomblachut** [comment]
Huh, interesting. Thanks for reporting.

**Comment by tomblachut** [comment]
Hello :) Could you see if adding any code after the import, still inside script tag prevents this problem? I suspect last error inside script tag is getting lost.

**Comment by tomblachut** [comment]
Migrating GH issues to YouTrack. I've created a new issue: 
[WEB-62296](https://youtrack.jetbrains.com/issue/WEB-62296) missing syntax error for unclosed string literal in ESM import statement
