### ISSUE TITLE
Update compatible version for WS2019.2 EAP

### ISSUE THREAD

**Issue by anstarovoyt** [tomblachut/svelte-intellij#23]
Hi! WS2019.2EAP is out and current available version of the plugin is not compatible with it (because of version range 2019.1.1 — 2019.1.3). Could you please update it?

**Comment by nightwolfz** [comment]
I managed to make 0.7.0 work by changing the version range.

https://megaupload.nz/b660Bfv3n9/svelte-intellijXXX_zip

**Comment by anstarovoyt** [comment]
@tomblachut any updates? We are going to release 2019.2 next week

**Comment by tomblachut** [comment]
Hey thanks for updates and your patience. I'm going to fix that shortly
