### ISSUE TITLE
Unexpected Cannot resolve file warning

### ISSUE THREAD

**Issue by louis77** [tomblachut/svelte-intellij#233]
I get a lot of these "Cannot resolver [property]" messages although the properties are clearly defined:

![Bildschirmfoto 2021-07-02 um 17 43 55](https://user-images.githubusercontent.com/1240462/124299127-5afe7880-db5d-11eb-8c6b-2a84d753a27e.png)

Looks to me that this happens with the `src` attribute most of the times.
Anything I can do about it?

**Comment by louis77** [comment]
Ok, so from what I understand this is not a problem of the Svelte plugin but from the IntelliJ/WebStorm linter that tries to load the url from tags with a `src` attribute. However that will never work in dynamic Svelte code. Is there any way the Svelte plugin can suppress these warning?

**Comment by tomblachut** [comment]
Hi, it could be suppressed indeed. Full featured support would require understanding of Svelte expressions by built-in IDE code

**Comment by tomblachut** [comment]
Since [v0.20.0](https://github.com/tomblachut/svelte-intellij/releases/tag/v0.20.0) those inspections are suppressed.
