### ISSUE TITLE
Enable ESLint for .svelte files

### ISSUE THREAD

**Issue by adrianmroz** [tomblachut/svelte-intellij#24]
As I understand, right now in WebStorm you can run eslint only against files with extensions associated with JavaScript. Svelte plugin has separate file type. 

If that's the case, it would be nice if we could get option to run eslint against .svelte files. Right now I managed run eslint from command line with https://github.com/sveltejs/eslint-plugin-svelte3 and works great.

**Comment by tomblachut** [comment]
Yeah I need to get to it. Thanks for reporting!

**Comment by shirotech** [comment]
I thought this used to be a deal-breaker without having eslint support. But if you add a watcher in settings to automatically run eslint every time the file is saved, this becomes less of a problem for now until eslint is properly supported.

**Comment by tomblachut** [comment]
@shirotech Nice! Personally I run linting during committing and pushing, using a combination of `husky` and `lint-staged`.

**Comment by shirotech** [comment]
> @shirotech Nice! Personally I run linting during committing and pushing, using a combination of `husky` and `lint-staged`.

Yeah and that too, but also the main advantage of the built-in `File Watchers` is it allows the IDE to sync the file that was changed. I couldn't find a way to do that with tools running outside of the IDE.

**Comment by tomblachut** [comment]
@anstarovoyt I wonder if you could take a look at that issue? Last time I've checked (a year ago), there were some file extensions hardcoded into the builtin ESLint code - e.g. `.vue` - and I didn't notice a way to extend that

**Comment by anstarovoyt** [comment]
@tomblachut yes, I will try to implement this

**Comment by tomblachut** [comment]
@anstarovoyt great, thanks

**Comment by anstarovoyt** [comment]
so. Actually you can enable the ESLint integration in the IDE by changing key in the Registry:
```
Help - Find Action - Registry
```
Key:
```
eslint.additional.file.extensions
```
Value
```
svelte
```
I am searching a better way to do it programmatically but it should work
<img width="697" alt="Screenshot 2020-08-06 at 19 40 56" src="https://user-images.githubusercontent.com/1753282/89558344-c2f8f180-d81c-11ea-91b0-fe97ec6663d1.png">
