### ISSUE TITLE
Required attributes on HTML elements don't recognize Svelte binding

### ISSUE THREAD

**Issue by TheOnlyTails** [tomblachut/svelte-intellij#243]
When using tags such as `img`, `head` (in the `app.html` file), etc. in Svelte components and using binding to add certain attributes:
```svelte
<img bind:alt={altText}/>
<img {src}/>
```
The IDE thinks the attributes are still missing and triggers the inspection.

**Comment by tomblachut** [comment]
Second case already works since 0.20.0

First one is indeed a bug.

**Comment by tomblachut** [comment]
Migrating GH issues to YouTrack. I've created a new issue:
[WEB-62305](https://youtrack.jetbrains.com/issue/WEB-62305) Svelte: suppress Missing required attribute inspection for bind: directive
