### ISSUE TITLE
No import intention available for actions

### ISSUE THREAD

**Issue by TheOnlyTails** [tomblachut/svelte-intellij#245]
Since actions use user-defined functions, it'll be nice to have an intention that imports them (similar to components).
![image](https://user-images.githubusercontent.com/65342367/130133910-c90a8e8e-d881-4534-b7a7-6a855b6f799d.png)

**Comment by NyxCode** [comment]
The same happens for transitions (`<div transition:slide={{.....}} />`)

**Comment by tomblachut** [comment]
Migrated to [WEB-61823](https://youtrack.jetbrains.com/issue/WEB-61823) Svelte: add auto-import in directives
