### ISSUE TITLE
Autocompletion suggests only one svelte component with different paths.

### ISSUE THREAD

**Issue by vgpechenkin** [tomblachut/svelte-intellij#246]
Hey.
If I have 2 svelte files with the same name. Autocompletion suggests only one.
![image](https://user-images.githubusercontent.com/1455274/130435794-35047d80-fadd-4350-b05e-debf855101a2.png)

**Comment by tomblachut** [comment]
Migrated to [WEB-61820](https://youtrack.jetbrains.com/issue/WEB-61820) Svelte: improve auto-import of components
