### ISSUE TITLE
Empty Tag Inspection Setting does not work

### ISSUE THREAD

**Issue by micschwarz** [tomblachut/svelte-intellij#248]
I'm using [Svelte Prettier](https://github.com/sveltejs/prettier-plugin-svelte) to reformat my code.
Empty Tags are converted from `<div class="foo"></div>` to `<div class="foo" />` which triggers a warning in the IDE. I would like to disable this warning, but the setting "Editor > Instpections >HTML> Empty tag" has no influence on svelte files. It would be great to have this feature, in order to customize the shown warnings

**Comment by tomblachut** [comment]
<img width="313" alt="image" src="https://user-images.githubusercontent.com/615013/146996881-99a73264-faec-4b36-970b-68d8e4d31937.png">
@micschwarz I was able to disable the inspection, which versions of IDE+plugin are you using?

**Comment by micschwarz** [comment]
@tomblachut I think this issue can be closed. I tried it with WebStorm 2021.3 and version 0.21.1 of the plugin and it works. I guess its fixed now 🥳
