### ISSUE TITLE
Variables created in reactive statements are marked as unresolved

### ISSUE THREAD

**Issue by TheOnlyTails** [tomblachut/svelte-intellij#249]
When I create a variable in a reactive statement like so:
```typescript
let count = 0;
$: doubled = count * 2;
```
The result is the following:
![image](https://user-images.githubusercontent.com/65342367/133892185-0d3df722-5bc6-46dc-94d9-04e49aeacaab.png)
In both the declaration site and any usage, the reactive variable is marked as unresolved.

**Comment by rafrafek** [comment]
I have the same problem in Pycharm Pro 2021.3
![obraz](https://user-images.githubusercontent.com/23004737/145010438-cff79cc0-bc63-4b55-a14e-747c7568f8ee.png)

**Comment by hiluw** [comment]
A workaround is to split the declaration and assignment:
```ts
let count = 0;

let doubled;
$: doubled = count * 2;
```

**Comment by AnthoniG** [comment]
> A workaround is to split the declaration and assignment:
> 
> ```ts
> let count = 0;
> 
> let doubled;
> $: doubled = count * 2;
> ```

Thanks I was banging my head against the wall with this, until eventually I had to remove the `lang="ts"` and fall back to plain JavaScript.

**Comment by tomblachut** [comment]
Folks, I tried to reproduce this across versions and reactive declarations always work for me no matter if in JS or TS script.
I'll need a reproduction project for this bug, I'm afraid.

**Comment by hiluw** [comment]
> Folks, I tried to reproduce this across versions and reactive declarations always work for me no matter if in JS or TS script.
> I'll need a reproduction project for this bug, I'm afraid.

This usually happens after you shut the IDE completely and reopen it

**Comment by TheOnlyTails** [comment]
Awesome, thank you!

**Comment by AndrewKirkovski** [comment]
Was there any regression recently?
I'm having this issue in PhpStorm in fresh project

Happens inconsistently, some places work ok, some not

<img width="456" alt="image" src="https://user-images.githubusercontent.com/16134699/185214066-66d76534-3306-472a-9e5d-a80cc685754b.png">

**Comment by TheOnlyTails** [comment]
I'm actually getting this too with the new SvelteKit changes:
```html
<script lang="ts">
  export let data;
  $: ({ posts } = data)
</script>
```

**Comment by tomblachut** [comment]
Folks, I'm assuming this is the 2022.2? Maybe something regressed in the core JS code, need to check

**Comment by Captain-Matroskin** [comment]
> Folks, I'm assuming this is the 2022.2? Maybe something regressed in the core JS code, need to check

The same problem now. I use WebStorm 2022.3

**Comment by Scui1** [comment]
Issue still persists in WebStorm 2023.1.2 together with plugin version 231.8770.15
![Image](https://i.imgur.com/wbi83X5.png)

**Comment by tomblachut** [comment]
Covered by some other issues and mostly [WEB-58397](https://youtrack.jetbrains.com/issue/WEB-58397) use the svelte language server
