### ISSUE TITLE
Plugin requires Intellij IDEA Ultimate Edition, but documentation says it supports Community Edition

### ISSUE THREAD

**Issue by Thunderforge** [tomblachut/svelte-intellij#250]
According to the project readme

> You'll need IntelliJ IDEA. The Community Edition is free and sufficient, you can also use Ultimate edition if you have one.

However, the plugin is only available from the [Intellij marketplace](https://plugins.jetbrains.com/plugin/12375-svelte) for Ultimate Edition. Searching the plugin marketplace in Community Edition shows no results.

<img width="982" alt="image" src="https://user-images.githubusercontent.com/6200170/135332482-da1f09f6-c0db-41f5-a3f1-66b1eb892054.png">

**Comment by tomblachut** [comment]
It's under `Contributing` section. Community Edition is sufficient because plugin is written in Kotlin, but requires JavaScript-enabled IDE, like WebStorm or IJ Ultimate, to run. (When contributing, correct version of development IDE is downloaded by Gradle)
