### ISSUE TITLE
code completion not working for npm installed project's svelte component

### ISSUE THREAD

**Issue by yslim** [tomblachut/svelte-intellij#253]
package.json
```json
   "devDependencies": {
      "@smui/button": "^5.0.0-beta.7",
```
```svelte
// index.svelte
<script lang="ts">
  import Button from "@smui/button"
</script>

<Button  variant="raised" class="mdc-ripple-upgraded">ClickMe</Button>
```

- problem: exported props not shown in WebStorm
  (but it works well for local project's svelte component )
<img width="721" alt="webstorm" src="https://user-images.githubusercontent.com/1180222/138394281-82ae7aa6-28a3-4115-9226-4e0ce0242e95.png">

- vscode works well
<img width="709" alt="vscode" src="https://user-images.githubusercontent.com/1180222/138394324-ebfe9626-85f2-4bff-a292-c9b658dd0536.png">

What settings should I change to make it work?

Thanks in advance.

**Comment by tomblachut** [comment]
Hello! This is not implemented yet, sorry. There's already issue about that: #206
