### ISSUE TITLE
Plugin throws errors in 2021.3 EAP

### ISSUE THREAD

**Issue by TheOnlyTails** [tomblachut/svelte-intellij#254]
I've updated the plugin to v0.21.1 (on build WS-213.5281.15), and immediately got the following errors in my SvelteKit-TypeScript project:
https://gist.github.com/TheOnlyTails/a37551774649cf0cc7eb8d4097983c38

It can't finish analyzing the files, making the plugin effectively useless.
Can this be resolved ASAP please?

**Comment by tomblachut** [comment]
This was a bug in AngularJS plugin most likely. I'm not aware of similar problems in stable 2021.3, so I'm closing the issue. Please let me know if something is still throwing.
