### ISSUE TITLE
since version 0.21.0 TypeScript imports shows error 'Cannot resolve symbol'

### ISSUE THREAD

**Issue by dadiborn** [tomblachut/svelte-intellij#255]
src/App.svelte :: import {myStore} from './folder/component.store'; << OK
src/folder/Component.svelte :: import {myStore} from './component.store'; << broken on 0.21.0 | OK on 0.20.0 
src/folder/component.store.ts

Version 0.20.0 was the last version where **component.store.ts** can be imported to **Component.svelte**  this way:
_import {myStore} from './component.store';_

All version above says "Cannot resolve symbol". 
On broken versions this can be fixed by adding .ts extension at the end on import like so:
_import {myStore} from './component.store.ts';_
This solution with adding extension is incorrect. The problem appears only on sub folders, import on root level works fine.

**Comment by dadiborn** [comment]
UPDATE: I found that this is naming conflicts. Even "Data.svelte" is starts with capital and in same directory "data.ts" is lowercase, it makes conflict and doesn't work properly. To solve this issue we need to move .ts to sub directory if we want to keep name or just rename it so component and ts files doesn't match.

**Comment by AnthoniG** [comment]
WebStorm Version: 2021.3
Plugin Version: 0.21.1

///////////////////////////////////////////////////////////////////////
I am also experiencing this
`// This will rename the database from "localforage"
  $: count = 0
  $: error = ''
  $: email = 'anthoni.me@gmail.com'
  $: password = 'password1234567890'
  $: disabled = email.trim() === '' || password.trim() === ''`

All variables are highlighted in red and WebStorm says "Unresolved variable or type <variable name>"

Was working earlier, but WebStorm was in constant analysing mode, so I restarted it.
Then all my code went red with errors in .svelte files

Project still runs and no errors in console nor in browser.

**Comment by Takitaf** [comment]
> WebStorm Version: 2021.3 Plugin Version: 0.21.1
> 
> /////////////////////////////////////////////////////////////////////// I am also experiencing this
> 
> ```
> // This will rename the database from "localforage"
>   $: count = 0
>   $: error = ''
>   $: email = 'anthoni.me@gmail.com'
>   $: password = 'password1234567890'
>   $: disabled = email.trim() === '' || password.trim() === ''
> ```
> 
> All variables are highlighted in red and WebStorm says "Unresolved variable or type "
> 
> Was working earlier, but WebStorm was in constant analysing mode, so I restarted it. Then all my code went red with errors in .svelte files
> 
> Project still runs and no errors in console nor in browser.

I have the same problem, also version 0.21.1. All of reactive variables behaves like that: 
![image](https://user-images.githubusercontent.com/24763213/147508060-8442e6a3-b365-4929-b283-fb3a9b11b7fa.png)

**Comment by dadiborn** [comment]
@Takitaf @AnthoniG
I haven't seen this reactive variable issues since  0.21.**2**
On my current setup with all latest updates (for IDE and Plugins) everything works perfectly, so try to update and run _File/Invalidate Caches..._

**Comment by tomblachut** [comment]
This issue was solved some time ago, apologies for not closing it here.
