### ISSUE TITLE
Auto Imports for TypeScript Components do not respect IDE Code Style Setting: Use paths relative to tsconfig.json

### ISSUE THREAD

**Issue by dadiborn** [tomblachut/svelte-intellij#256]
For components thats use  lang="ts", auto imports of other (nested) components do not respect IDE Setting:
_Settings/Editor/Code Style/TypeScript_ : **Use paths relative to tsconfig.json** [unchecked]

And to get relative path for components thats use  typescript, additionally to unchecked setting above, we need to uncheck similar for JavaScript:
_Settings/Editor/Code Style/JavaScript_ :  **Use paths relative to the project, resource or source roots**

When both unchecked, auto import of .svelte components uses relative paths and works as expected

**Comment by tomblachut** [comment]
Hello, can you provide sample reproduction and version of IDE and plugin used? This should work in newest versions

**Comment by tomblachut** [comment]
Migrated to [WEB-54246](https://youtrack.jetbrains.com/issue/WEB-54246) Svelte plugin imports using .js extension on TypeScript blocks
