### ISSUE TITLE
Support for namespaced components

### ISSUE THREAD

**Issue by unlocomqx** [tomblachut/svelte-intellij#257]
Hi, I used this code from `svelte-cubed`
https://svelte-cubed.vercel.app/docs/getting-started

```svelte
<script>
	import * as THREE from 'three';
	import * as SC from 'svelte-cubed';
</script>

<SC.Canvas>
	<SC.Mesh geometry={new THREE.BoxGeometry()} />
	<SC.PerspectiveCamera position={[1, 1, 3]} />
</SC.Canvas>
```

The extension didn't highlight the code correctly or detect that the import is used

<img width="453" alt="2021-11-24 at 4 54 PM" src="https://user-images.githubusercontent.com/793712/143271612-89f79c08-41d8-4383-9b79-bfe62e2b31c1.png">

**Comment by russelldavis** [comment]
Looks like this may be a dup of #8. @tomblachut any update on that? You wrote there that it was blocked on #2, but that has since been fixed.

**Comment by unlocomqx** [comment]
@russelldavis Yeah I forgot about that issue, I've seen a long time ago
I'll close this one then
Cheers
