### ISSUE TITLE
Component doesn't see values imported in external script file

### ISSUE THREAD

**Issue by pavel-krasnov** [tomblachut/svelte-intellij#265]
When using a svelte-preprocess [external files](https://github.com/sveltejs/svelte-preprocess#external-files) feature I create an external TypeScript file for a component and assign some values to variables in there and import something else to it, the Svelte component I then use this .ts file in marks the imports as not imported. On the other end, the value used in the component remains "unused" in the .ts files. The preprosessor itself works correctly and provides the values as it should.

![Screenshot from 2021-12-31 13-24-19](https://user-images.githubusercontent.com/33923235/147823305-f0ff5023-4bc5-42f6-98e1-336d5e7caac8.png)

![Screenshot from 2021-12-31 13-24-34](https://user-images.githubusercontent.com/33923235/147823306-b38a9832-500f-46f8-8121-40617b954cb6.png)

**Comment by tomblachut** [comment]
Please open an issue on YouTrack, thank you!
