### ISSUE TITLE
Support the {@const} tag

### ISSUE THREAD

**Issue by TheOnlyTails** [tomblachut/svelte-intellij#268]
The `{@const}` tag, which allows declaration of constants inside markup, is soon to be merged into the main Svelte repo: https://github.com/sveltejs/svelte/pull/6413

Some opportunities this can have:
- TypeScript support
- Auto-completion support in markup (including variables declared with `{@const}` in auto-completion)
- Support for Navigate-to-declaration & Find Usages
(you get the point, it should behave like any other variable declared with `const`)

https://svelte.dev/docs#template-syntax-const

The language tools PR has already been merged: https://github.com/sveltejs/language-tools/pull/1319
The RFC describing the syntax: https://github.com/sveltejs/rfcs/blob/master/text/0007-markup-constants.md

Update: `{@const}` has now been officially released in Svelte 3.46.

**Comment by risalfajar** [comment]
will this be supported soon?

**Comment by cristianvogel** [comment]
The plugin really needs `{@conts}`  support to be complete. 
https://svelte.dev/docs#template-syntax-const

**Comment by risalfajar** [comment]
@tomblachut is there any plan for this? It has been 9 months :(

**Comment by risalfajar** [comment]
Update: Issue tracking has been moved from GitHub to YouTrack

see https://youtrack.jetbrains.com/issue/WEB-55903/Svelte-const-tag-causes-syntax-errors
