### ISSUE TITLE
Support TypeScript literal strings in components

### ISSUE THREAD

**Issue by MarvinJWendt** [tomblachut/svelte-intellij#269]
```typescript
export let size: "medium" | "large" | "small" = 'medium';
```

This limits the attribute size to be one of ["medium", "large", "small"].
I think it would be nice to have those options in the autocomplete when using the attribute:

![image](https://user-images.githubusercontent.com/31022056/149049889-36a0ce1f-f5e3-42c8-9f15-f6e4ac8a87a9.png)

**Comment by tomblachut** [comment]
Duplicate/subset of #220
