### ISSUE TITLE
Support more complex Navigate To Declaration behavior

### ISSUE THREAD

**Issue by TheOnlyTails** [tomblachut/svelte-intellij#271]
Currently, the only support we have for Navigate To Declaration in Svelte HTML is back to components, from a component name in a tag.

I suggest the following:
- Props: when navigating to declaration on a property, it will search for an `export let/const prop` statement in the relevant component and navigate there.
- Slots: when navigating to declaration on a `<svelte:fragment slot="">`, it should find the corresponding `<slot name="">` in the component.
- etc.

**Comment by tomblachut** [comment]
Migrated to [WEB-61565](https://youtrack.jetbrains.com/issue/WEB-61565) Use Go To Definition from Svelte Language Server
