### ISSUE TITLE
Support for WebStorm 2022.1 EAP

### ISSUE THREAD

**Issue by wiesson** [tomblachut/svelte-intellij#276]
As with every EAP version, the plugin is not supported 😅 

<img width="426" alt="Screenshot 2022-03-13 at 13 19 49" src="https://user-images.githubusercontent.com/933231/158059081-2ef37936-a6c9-4642-a9c7-c010c5f83d09.png">

It would be nice if I could test the EAP with the svelte-intellij plugin!

**Comment by tomblachut** [comment]
Hi, here's a build for the impatient :) It will be published to the Marketplace later. We had some uncoordinated breaking changes in the platform, unfortunately it's not easy keeping this plugin available during all EAP.

[svelte-intellij-0.22.0.zip](https://github.com/tomblachut/svelte-intellij/files/8343226/svelte-intellij-0.22.0.zip)

**Comment by wiesson** [comment]
<img width="406" alt="Screenshot 2022-03-24 at 18 37 38" src="https://user-images.githubusercontent.com/933231/159976919-2f513037-bfae-4bc4-a886-ff638baf4183.png">

Thank you!!

**Comment by tomblachut** [comment]
https://github.com/tomblachut/svelte-intellij/releases/tag/v0.22.0 is now available in the Marketplace, so I'm closing the issue.
