### ISSUE TITLE
version 0.22.0 is not compatible with WebStorm 2021.3.3

### ISSUE THREAD

**Issue by mike-odom** [tomblachut/svelte-intellij#282]
WebStorm 2021.3.3
Build #WS-213.7172.31, built on March 18, 2022

I'm excited to see a new build out!

I just downloaded the latest release and did 'Plugins -> Install Plugin from Disk' and got the below error message

_Plugin 'Svelte' (version '0.22.0') is not compatible with the current version of the IDE, because it requires build 221.5080 or newer but the current build is WS-213.7172.31_

<img width="551" alt="image" src="https://user-images.githubusercontent.com/5105729/160953979-7da78660-5155-4032-8c03-f53f63cc3561.png">

**Comment by tomblachut** [comment]
Yes, that was mentioned in the release notes "Compatibility with 2022.1 platform", I could've added some clarifying adjective, that it meant lower bound.
