### ISSUE TITLE
Wrongly supporting #each with index as first parameter

### ISSUE THREAD

**Issue by avi12** [tomblachut/svelte-intellij#283]
In my code I had something like:
```svelte
<script>
  const obj = {
    key: "foo"
  };
</script>

{#each obj as i, { key }}
  {key}
{/each}
```
I learned the [hard way](https://svelte.dev/tutorial/each-blocks) that the `i` should come *after* the `{ key }`, not before it, i.e.
```svelte
{#each obj as { key }, i}
  {key}
{/each}
```
The plugin did not report anything wrong, which resulted in Prettier failing and I wasn't sure why. Took me a while to figure that one out
Plugin version: 0.21.2

**Comment by tomblachut** [comment]
Handled by the language server, kind of, [WEB-58397](https://youtrack.jetbrains.com/issue/WEB-58397) use the svelte language server
