### ISSUE TITLE
Support for path alias is broken

### ISSUE THREAD

**Issue by korywka** [tomblachut/svelte-intellij#284]
new svelte kit uses `extend` inside `jsconfig.json`:

```
{
	"extends": "./.svelte-kit/tsconfig.json"
}
```

looks like webstorm doesn't follow it and can't resolve path alias:

```
import { requestJSON } from '$lib/request.js';
```

<img width="655" alt="image" src="https://user-images.githubusercontent.com/988471/163034221-8d171444-e6f0-4abf-a9b7-5d610eefa63e.png">

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/988471/163034280-abde94e5-9b9c-4da4-9200-f5162b0dd7e7.png">

```
WebStorm 2022.1
Build #WS-221.5080.193, built on April 10, 2022
Licensed to MacPaw / Taras Neporozhniy
Subscription is active until March 31, 2023.
Runtime version: 11.0.14.1+1-b2043.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    eslint.additional.file.extensions=svelte

Non-Bundled Plugins:
    org.toml.lang (221.5080.126)
    org.rust.lang (0.4.168.4555-221)
    dev.blachut.svelte.lang (0.22.0)
```

**Comment by korywka** [comment]
Looks like it doesn't work without extends too. Can someone confirm please?

**Comment by Maggi64** [comment]
@korywka I resolved problems with linking of internal packages by downgrading to webstorm 2021.3.3.
Maybe try that for now.

**Comment by korywka** [comment]
I solved it with migrating to VSCode. WebStorm very nice IDE with such poor quality Svelte support. Not going to renew my license 😕

**Comment by tomblachut** [comment]
Not a problem in Svelte plugin. Should be working in 2023.1 already.
