### ISSUE TITLE
Support dynamic elements via `<svelte:element>` released in svelte 3.47.0

### ISSUE THREAD

**Issue by dominikg** [tomblachut/svelte-intellij#285]
docs: https://svelte.dev/docs#template-syntax-svelte-element

changelog: https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#3470

PR: https://github.com/sveltejs/svelte/issues/2324

**Comment by dominikg** [comment]
#language-tools on [svelte discord](https://svelte.dev/chat)  is a great place if you have questions.

**Comment by julienchazal** [comment]
hello, +1 for this feature

build should not be broken if we use `svelte:element` (error `Valid <svelte:...> tag names are svelte:head, svelte:options, svelte:window, svelte:body, svelte:self, svelte:component or svelte:fragment`)

thx

**Comment by tomblachut** [comment]
Migrating GH issues to YouTrack. I've created a new issue: 
[WEB-62309](https://youtrack.jetbrains.com/issue/WEB-62309) Svelte: add completion of svelte:element

the rest should be supported already via [WEB-58397](https://youtrack.jetbrains.com/issue/WEB-58397) use the svelte language server.
