### ISSUE TITLE
TypeScript declare module doesn't resolve for wildcards syntax

### ISSUE THREAD

**Issue by shir0u** [tomblachut/svelte-intellij#289]
For example, in `index.d.ts` we define override for importing from different extensions, in this case, `.scss`.

```ts
declare module '*.scss' {
  export function renderStyles(vars: {[prop: string]: string}): void;
}
```

Then in `app.svelte`:
<img width="390" alt="Screen Shot 2022-05-14 at 10 48 24 am" src="https://user-images.githubusercontent.com/85612853/168404546-eb6e878e-ab7f-462a-8784-b08574fe8d67.png">

But in `app.ts` works fine:
<img width="379" alt="Screen Shot 2022-05-14 at 10 49 11 am" src="https://user-images.githubusercontent.com/85612853/168404569-cef162b5-f3a5-4938-a773-92325b6facef.png">

**Comment by tomblachut** [comment]
We made lots of improvements around this problem during the last year.
If the issue still persist please open another issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=WEB).
