### ISSUE TITLE
Generated types dir is not recognized in Svelte compoenents

### ISSUE THREAD

**Issue by TheOnlyTails** [tomblachut/svelte-intellij#292]
When trying to use generated types for the `load` function in SvelteKit, as such:
```html
<script context="module" lang="ts">
  import type { Load } from "./__types/index";
</script>
```
I get the following error: 
![image](https://user-images.githubusercontent.com/65342367/172633404-60555046-7ea4-4cb8-80e7-420df41794a4.png)

my `tsconfig.json` is the standard one from the template:

<details>
<summary>Details</summary>

```json
{
	"extends": "./.svelte-kit/tsconfig.json",
	"compilerOptions": {
		"allowJs": true,
		"checkJs": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": true
	}
}
```

</details>

And the generated types work as expected in regular typescript files.

(Note: the aliases declared in SvelteKit's generated `tsconfig.json` work just fine. It's just the generated typedefs themselves which don't work)

**Comment by TheOnlyTails** [comment]
Now that https://github.com/sveltejs/kit/pull/5778 is merged, all page data is now typed with these generated props, which makes this very vital to have. Could this please be implemented soon?

**Comment by TheOnlyTails** [comment]
For now, a possible hack is to specify the full URL, but this just looks extremely fugly:
```html
<script lang="ts">
    import type { PageData } from ".svelte-kit/types/src/routes/$types";
</script>
```

**Comment by dummdidumm** [comment]
What exactly is the error you are getting / what is wrong? I don't see anything red in the screenshot.

**Comment by TheOnlyTails** [comment]
the `__types` directory is red. Here's a screenshot from the new `$types` dir:
![image](https://user-images.githubusercontent.com/65342367/184875085-a74c5424-ed0e-4cd9-9332-eb4ef47d9691.png)

**Comment by dummdidumm** [comment]
I can't reproduce this given the instructions. Please provide a proper minimum reproducible.

**Comment by tomblachut** [comment]
Migrating to YouTrack... Kind of an old issue, it works in 2023.1/2023.2.
