### ISSUE TITLE
Comment with Line Comment broken for <script> section of .svelte files

### ISSUE THREAD

**Issue by indigo-jay** [tomblachut/svelte-intellij#294]
When I try to comment out the subscribe code section below using CMD-/ (macOS) in a svelte file:

	<script>
		import DeviceFolderStore from "./stores/deviceFolderStore";
	
		let deviceFolders = [];
	
		DeviceFolderStore.subscribe(data => {
			deviceFolders = data;
		});
	</script>

This is the result:

	<script>
		import DeviceFolderStore from "./stores/deviceFolderStore";
	
		let deviceFolders = [];
	
		
		
		
	</script>

So, it seems comments inside the <script> tag are HTML comments rather than JavaScript comments.

**Comment by indigo-jay** [comment]
Note, this is in PyCharm - not sure if that makes a difference.

**Comment by planetaska** [comment]
Same issue here with WebStorm. Is there a possible fix?

**Comment by tomblachut** [comment]
Looks like a regression unrelated to Svelte plugin that was already fixed in WebStorm. If the problem persists please create an issue on YouTrack, thanks!
