### ISSUE TITLE
Add support for `context="module"`

### ISSUE THREAD

**Issue by petermakeswebsites** [tomblachut/svelte-intellij#296]
Looks like there is no proper support for module context so I'm throwing this in here to put on the to-do list

Example.svelte
```svelte
<script lang="ts" context="module">
import { writable } from "svelte/store"
export const animal = writable("tiger")
</script>
Animal is a {$animal}
```

Second.svelte
```svelte
<script lang="ts">
import { animal } from "Example.svelte" // Cannot resolve symbol 'headerAnimationsReady'
</script>
Imported animal is a {$animal}
```

**Comment by r00t3g** [comment]
Looks like dupe https://github.com/tomblachut/svelte-intellij/issues/241

**Comment by tomblachut** [comment]
Migrated to [WEB-54714](https://youtrack.jetbrains.com/issue/WEB-54714) Svelte: modules exported from a 'context="module"' script block of the other component not resolved
