### ISSUE TITLE
Connect instance script with template expressions for code insight

### ISSUE THREAD

**Issue by tomblachut** [tomblachut/svelte-intellij#3]
It will fix unused imports problem and improve rename refactoring

**Comment by CreaturesInUnitards** [comment]
> It will fix unused imports problem [...]

Is this referring to imports appearing as unused if they're not used inside a `<script>`?

**Comment by tomblachut** [comment]
Exactly

**Comment by tomblachut** [comment]
While #28 fixes unused imports problem main script is still disconnected from template expressions so for example variables aren't referenced by usages

**Comment by unlocomqx** [comment]
Here's some insight from the jetbrains guys
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004357879-Different-behavior-between-LanguageInjector-and-MultiHostInjector
