### ISSUE TITLE
Auto-import does not emit `import type` for types

### ISSUE THREAD

**Issue by NyxCode** [tomblachut/svelte-intellij#300]
When auto-importing TypeScript types, the plugin inserts a normal `import { Type1, Type2 } from "somewhere"` import, even though `compilerOptions.importNotUsedAsValues`  is set to `"error"` in `.svelte-kit/tsconfig.json`.  
The proper import would be `import type { Type1, Type2 } from "somewhere"`.

**Comment by tomblachut** [comment]
Works in 2023.1/2023.2
