### ISSUE TITLE
destructed exports are not suggested

### ISSUE THREAD

**Issue by FluffyDiscord** [tomblachut/svelte-intellij#302]
If we have

```html
<script>
    let className

    export { className as class }
    export let test
</script>
```

IDE does not suggest exported `class` as a valid prop

![obrazek](https://user-images.githubusercontent.com/10332247/182217990-8f8f9a48-20f7-4555-846c-1a7dabb17eff.png)

but the "normal" one works

![obrazek](https://user-images.githubusercontent.com/10332247/182218149-7bd76c68-8503-4279-a047-87626b6d4c6b.png)

Both are valid in svelte https://svelte.dev/docs#component-format-script-1-export-creates-a-component-prop

**Comment by tomblachut** [comment]
Handled with Language Server in the 2023.2 IDE releases.
