### ISSUE TITLE
typescript declarations not working correctly for derived stores.

### ISSUE THREAD

**Issue by srsholmes** [tomblachut/svelte-intellij#303]
In some cases when using a derived store, the types are reported incorrectly. The return value of the derived store in this case in is a generated sdk from a Graphql Schema using https://www.graphql-code-generator.com. 

As you can see, the method on the client has no declaration, jump to definition does not work, and as a result, the result from the method has no types. There are also no type errors for the input to the method.

This all works fine in VScode. 

In VScode:
<img width="457" alt="Screenshot 2022-08-05 at 11 48 43" src="https://user-images.githubusercontent.com/3579905/183062338-db3eef0b-465c-4a1f-bfa2-8a01d48b591c.png">

In Webstorm: 
<img width="488" alt="Screenshot 2022-08-05 at 11 48 27" src="https://user-images.githubusercontent.com/3579905/183062410-29579768-ed53-49d0-8b8f-51a065aae3cf.png">

<img width="592" alt="Screenshot 2022-08-05 at 11 51 33" src="https://user-images.githubusercontent.com/3579905/183062670-58a9ffbb-4a58-4d98-afb3-890d0a3ee026.png">

**Comment by tomblachut** [comment]
Should be contained in [WEB-58397](https://youtrack.jetbrains.com/issue/WEB-58397) use the svelte language server.
