### ISSUE TITLE
No errors on missing 'type' imports

### ISSUE THREAD

**Issue by srsholmes** [tomblachut/svelte-intellij#305]
Webstorm.
<img width="946" alt="image" src="https://user-images.githubusercontent.com/3579905/185096314-a9c1b4c4-b4b6-46fa-b099-e336bfc12c99.png">

Vscode:
![image](https://user-images.githubusercontent.com/3579905/185096248-beb5fa31-a4e3-45d2-bfb0-9bf8ac3c7523.png)

Webstorm does not report error when the type keyword is missing from imports. When Webstorm auto imports the types, this breaks the build.

**Comment by srsholmes** [comment]
related to https://github.com/tomblachut/svelte-intellij/issues/300

**Comment by tomblachut** [comment]
Contained in [WEB-58397](https://youtrack.jetbrains.com/issue/WEB-58397) use the svelte language server.
