### ISSUE TITLE
type errors not showing on component props

### ISSUE THREAD

**Issue by srsholmes** [tomblachut/svelte-intellij#306]
Webstorm does not show type errors on component props. 

Webstorm:
<img width="582" alt="Screenshot 2022-08-17 at 11 32 58" src="https://user-images.githubusercontent.com/3579905/185098218-c83f431e-c047-477e-ab82-d3f5e19bb7a3.png">

Vscode:
![Screenshot 2022-08-17 at 11 32 50](https://user-images.githubusercontent.com/3579905/185098221-9ff3d928-98ef-4633-8fce-8c30dab2971f.png)

related to 
https://github.com/tomblachut/svelte-intellij/issues/220
https://github.com/tomblachut/svelte-intellij/issues/207
https://github.com/tomblachut/svelte-intellij/issues/252

**Comment by Grawl** [comment]
Just tried Svelte after two years and faced this issue on my own.

Then I opened my project in VSCode and there is no "go to definition" from props.

I'n sad now

**Comment by tomblachut** [comment]
Contained in [WEB-58397](https://youtrack.jetbrains.com/issue/WEB-58397) use the svelte language server
