### ISSUE TITLE
`typeof` not hinted/colored in Svelte files

### ISSUE THREAD

**Issue by AlbertMN** [tomblachut/svelte-intellij#308]
Whether within the `<script>` tag, or in `{}` within the HTML part, the `typeof` operator doesn't get its usual color _(orange, by default)_, but is rather the same gray color as variables.

In all JavaScript files, its color is correct.

Minor issue, just something I've noticed.

**Comment by tomblachut** [comment]
It's a regression not in Svelte plugin that was fixed some time ago.
