### ISSUE TITLE
Reference to `./$types` does not work in .svelte files but works in .ts files

### ISSUE THREAD

**Issue by martinbeentjes** [tomblachut/svelte-intellij#309]
When importing a SvelteKit type (e.g. `PageData`) in a `.svelte` file, the IDE thinks it does not know `$types`. When importing a SvelteKit type (e.g. `PageServerLoad`) from a .ts file, it does work properly.

![Schermafbeelding 2022-08-30 om 14 41 54](https://user-images.githubusercontent.com/8865313/187439356-5ddf07fd-b31e-4c66-a206-39ad11562d99.jpg)

![Schermafbeelding 2022-08-30 om 14 42 05](https://user-images.githubusercontent.com/8865313/187439362-61f99115-3e8e-47c3-b25b-13c8fb347864.jpg)

---
**Edit [30th of August]:** I have rephrased the issue to the issue I am actually facing. Text below was original text

~~I am upgrading one of my projects to the newest version SvelteKit. I am seeing some errors in my code which are not errors. So an error inside Webstorm and the Svelte plugin.~~

~~Since the new router changes to SvelteKit, there are some errors in the plugin. For example, the following error. `Module '"./$types"' has no exported member 'Load'.` This happens on an `import type { Load } from './$types';`~~

~~How can I assist in fixing these? Where do I start?~~

**Comment by MFerraz** [comment]
These files are generated automatically on the `.svelte-kit/types` folder as part of the npm lifecycle. I believe you can force them to be generated using `npx svelte-kit sync` ([docs](https://kit.svelte.dev/docs/cli#svelte-kit-sync)). I believe this may solve your issue.

However, after they are generated, I'm getting another issue on svelte files when trying to import `./$types` - `Cannot resolve file '$types'`

It is working on VSCode, and it is also working when the import is on a Typescript file. The error only shows on the script tag of svelte files when running WebStorm

**Comment by martinbeentjes** [comment]
I'll adapt this issue, I was indeed making a mistake myself. However, I am having the same issue as you, with `./$types` unknown.

One to investigate, I am also having some issues with duplicate code. But that was fixed by marking the `.svelte-kit` folder _excluded_.

**Comment by bhvngt** [comment]
I was facing similar issues. I changed my `tsconfig.json` to include files from `root` dir. That seems to have fixed the import of `./$types`. However, in `+page.svelte` file, while it correctly imports `PageData` type, `data` variable still stays untyped.

Here's the screenshot of my setup.

![image](https://user-images.githubusercontent.com/79074469/186686121-6cbe3090-5826-48de-b488-ecf04d19e738.png)

**Comment by martinbeentjes** [comment]
Seems this is unrelated to the plugin, but a Webstorm issue.

**Comment by dennisjlee** [comment]
@martinbeentjes do you know if there is a separate issue we can follow for the underlying Jetbrains / Webstorm problem here?

**Comment by martinbeentjes** [comment]
https://youtrack.jetbrains.com/issue/WEB-57119/rootDirs-specified-in-tsconfigjson-not-respected-when-resolving-imports-in-svelte-files
