### ISSUE TITLE
Update on plugin release schedule

### ISSUE THREAD

**Issue by tomblachut** [tomblachut/svelte-intellij#311]
Hi folks,

as you might know already, for the last few years the WebStorm team have been responsible for the Svelte plugin in JetBrains Marketplace.

Starting from the 2022.3 release and the upcoming EAP, the Svelte plugin will be published at the same time as our IDEs – the same way the Angular and Vue plugins are published. It’ll mean there are no more problems with incompatible version ranges, especially during the EAP, and a faster feedback loop for our team. The first WebStorm 2022.3 EAP build will already contain some improvements, and we'll work on supporting recent additions to the framework, adding new features, and fixing existing bugs. Please note, Svelte plugin still won't be bundled into WebStorm so far.

Please check the [Svelte tag](https://youtrack.jetbrains.com/issues/WEB?q=tag:%20Svelte) for separate issues on specific improvements, and as usual, please upvote the existing issues or create new ones if you feel that something is missing.

N.B. There are also issues created here on the GitHub repository, please refrain from creating new issues here and choose YouTrack instead. Later we'll migrate these existing issues to YouTrack.

**Comment by risalfajar** [comment]
> There are also issues created here on the GitHub repository, please refrain from creating new issues here and choose YouTrack instead. Later we'll migrate these existing issues to YouTrack.

There are lots of issues in YouTrack that aren't resolved or even responded after months.

**Comment by r00t3g** [comment]
@risalfajar as stated in the official WS blog (https://blog.jetbrains.com/webstorm/2022/12/webstorm-2023-1-roadmap/), there are plans to improve Svelte support as of 2023.1 release. Personally, I''m gonna try the EAP as soon as the first stable builds are available.

**Comment by risalfajar** [comment]
@r00t3g I don't understand why they don't just start fixing the issues from now, so we don't need to wait until the end of March.

**Comment by r00t3g** [comment]
@risalfajar I suppose, primarily because now the Svelte plugin is not just a @tomblachut 's personal project, but a part of the big enterprise machine, which follows its release cycle.
