### ISSUE TITLE
syntax highlightnig bugs

### ISSUE THREAD

**Issue by KnightSlayer** [tomblachut/svelte-intellij#33]
![image](https://user-images.githubusercontent.com/9610676/61592297-2fde2100-abf3-11e9-8e05-0537aad7ce81.png)

There are 2 problems on this screenshot:
1)  {#each prhasesIds as phraseId} highlightnig wrong 'as'
2) import of Phrase component is grey but it used on string 58

**Comment by tomblachut** [comment]
Hello! Thanks for raising. Both fixed should be released in a couple of days.
1. Is tracked in #20 and worked on in #18 
2. Was fixed in #28
