### ISSUE TITLE
Importing components from npm modules doesn't work

### ISSUE THREAD

**Issue by M4v3R** [tomblachut/svelte-intellij#37]
This is for version 0.8.0.

When I import components using their npm names it doesn't work, i.e. the IDE gives an "Unresolved Svelte component" error. Here's a minimal reproduction:

```js
<script>
  import MyComponent from "./MyComponent.svelte";
  import {Router, Route} from "svelte-routing";
  export let url = "";
</script>

<main>
  <Header />
  <Router url="{url}">
    <Route path="/"><MyComponent/></Route>
  </Router>
</main>
```

This gives "Unresolved Svelte component" error for `Router` and `Route` components. Notice that importing components from a file works, as does importing from `svelte-routing` like the IDE suggests:

```js
  import Router from "../../node_modules/svelte-routing/src/Router.svelte";
  import Route from "../../node_modules/svelte-routing/src/Route.svelte";
```

**Comment by tomblachut** [comment]
Ah snap we need to conditionally suppress this inspection until proper support for node modules is implemented

**Comment by bevand10** [comment]
On a connected note, is this every likely to be supported?

```
import Header from "http://my-internal-shared-component-repo.corp.co.uk/Header.svelte";
```

**Comment by tomblachut** [comment]
@bevand10 never seen that one. How does it work in command line?
