### ISSUE TITLE
Support $ autosubscription syntax (store references)

### ISSUE THREAD

**Issue by tomblachut** [tomblachut/svelte-intellij#4]

**Comment by tomblachut** [comment]
I've been thinking about that for a bit now and finally asked JB for input.

Basically I see 2 approaches here: 
1. Extend JS language/parser (and also TS ones). Turns out this is insanely over-complicated because there are edge-cases in Svelte 😉 Svelte handles this after parsing step because it doesn't need to care about editing features.
2. Monkey-patch this on top of JS identifiers/references. I still don't know how to handle types but hey, TS is not supported anyway yet.

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004377420-Treat-part-of-JS-identifier-specially-depending-on-context

I guess preliminary type-unsafe support will be easy enough.

**Comment by unlocomqx** [comment]
I gave it a shot in my "reactive" branch. it's not so great but it could be helpful
https://github.com/unlocomqx/svelte-intellij/tree/reactive
- it links the $ prefixed expression with the "original" expression
- it provide completion by ignoring the $ prefix
I couldn't find a way to provide a type yet, I also didn't test the rename feature

**Comment by tomblachut** [comment]
Thx! I'll give it a spin

**Comment by today-** [comment]
Great job on last update. Now $stores are reconginzing and highlighting by IDE.

But TS-types are incorrent, now they show Store's type, not the value istelf.

I tried to evaluate Type from .subscribe() method as Svelte do and created such snippet

```typescript
type Unsubscriber<T extends {subscribe: any}> = T['subscribe'] extends ((v: infer S) => any) ?
  (S extends (v: infer V) => any ? V : never) : never;

type StoredValue = Unsubscriber<typeof store>;
```

**Comment by tomblachut** [comment]
@today- Current implementation is pretty stupid unfortunately

find usages action also don't find them properly

**Comment by tomblachut** [comment]
There's progress

![image](https://user-images.githubusercontent.com/615013/90342099-d585de80-e005-11ea-9d08-705eb8773b80.png)
