### ISSUE TITLE
Store and transitions imports not detected

### ISSUE THREAD

**Issue by pablote** [tomblachut/svelte-intellij#44]
Some imports are still not being detected as being used. Mainly transitions, and stores, which are not detected if using autosubscriptions with the $ sign. Btw, these two also show alerts when being used correctly:

![image](https://user-images.githubusercontent.com/2463995/62505497-4f6c7080-b7d3-11e9-987e-e8d4d87d69d2.png)

![Screen Shot 2019-08-05 at 22 49 28](https://user-images.githubusercontent.com/2463995/62505518-6743f480-b7d3-11e9-86b8-11292c3b13b0.png)

![Screen Shot 2019-08-05 at 22 49 35](https://user-images.githubusercontent.com/2463995/62505525-6ad77b80-b7d3-11e9-9783-6dc5a5c2c475.png)

Great work on this plugin, much appreciated.

**Comment by tomblachut** [comment]
Thanks, I'm happy you find this plugin valuable.

Everything inside tags besides names are treated as plain HTML now. Related issues: #2 and #11. 
I still don't know how to approach this because too many things seem to be interconnected.

$ operator is tricky, this is being tracked in #4.

**Comment by tomblachut** [comment]
Closing as duplicate
