### ISSUE TITLE
CSS class autocompletion

### ISSUE THREAD

**Issue by headphonejack** [tomblachut/svelte-intellij#60]
HTML templates detect and offer autocompletion for css classes in your project:

![image](https://user-images.githubusercontent.com/17085495/64936400-abec9200-d84d-11e9-96b9-0696f455ae07.png)

Svelte files don't do the same, do we know the limitations to doing this?

![image](https://user-images.githubusercontent.com/17085495/64936425-c9b9f700-d84d-11e9-8ed0-22075d84b2ae.png)

**Comment by tomblachut** [comment]
Hi! From the perspective of IDE Svelte is another language so everything need to be enabled separately. There is some extension point missing, from top of my head I guess something in css namespace or `CompletionContributor`. If you or anyone else wants to tackle this good starting point is to look at Angular or Vue plugin. I can also make some further research.

**Comment by AleksandrSl** [comment]
Hi! If nobody mind I can try to tackle this

**Comment by tomblachut** [comment]
@AleksandrSl that would be great!

**Comment by tomblachut** [comment]
Fixed in #70
