### ISSUE TITLE
Feature Request: Option To Auto Complete Only The Tag Name (and not all available params)

### ISSUE THREAD

**Issue by elliotwaite** [tomblachut/svelte-intellij#62]
It would be nice if there was an option to make the auto-complete feature only complete the tag name and not also add in all the available params, as sometimes the list of available params can be quite long and I may only want to set one of them, or often none of them.

Here's a video demo of the auto-complete adding all the available params where I would only want the tag name: https://youtu.be/fr7yT8QJGxg

**Comment by tomblachut** [comment]
I was thinking about creating settings page with - among others - swich related to that.

**Comment by elliotwaite** [comment]
Nice.

By the way, thanks for making this plugin, it's been very helpful.

**Comment by tomblachut** [comment]
Mentioned feature was buggy and I'm deleting it altogether.

Someday I'd like to prepare separate completion that inserts all missing props should the developer wish so.
