### ISSUE TITLE
stylelint support?

### ISSUE THREAD

**Issue by shirotech** [tomblachut/svelte-intellij#69]
Great plugin 👍 

I'm just wondering if this supports stylelint?

i.e.

```html
<style type="text/scss">
  .parent {
    .child {
    //
    }
  }
</style>
```

I can't seem to find a way for stylelint to work in this block.

**Comment by tomblachut** [comment]
Probably not. Would be nice if somebody confirmed whether Vue supports that, as that files are conceptually similar

**Comment by shirotech** [comment]
@tomblachut I just tried the Vue plugin, they do indeed support it, I would really want to help implement this but my Java are rather limited. Thank you in advance.

<img width="613" alt="Screen Shot 2019-10-27 at 10 07 29 am" src="https://user-images.githubusercontent.com/1149825/67627106-d6e0f180-f8a1-11e9-8d1c-841c9c937899.png">

**Comment by shirotech** [comment]
They also support eslint in `<script>` tags as well, perhaps you can borrow some of their code? This is in regarding https://github.com/tomblachut/svelte-intellij/issues/24

<img width="511" alt="Screen Shot 2019-10-27 at 10 11 32 am" src="https://user-images.githubusercontent.com/1149825/67627127-37702e80-f8a2-11e9-8070-3b5102e4df96.png">

**Comment by tomblachut** [comment]
Stylelint is supported (IDK how long 😅), closing.

![image](https://user-images.githubusercontent.com/615013/90322617-a9f7eb00-df56-11ea-8b06-43cd81c9430b.png)
