### ISSUE TITLE
Add completions for :global(...) modifier in styles

### ISSUE THREAD

**Issue by AleksandrSl** [tomblachut/svelte-intellij#71]
`<style>`  blocks in components can have `:global(...)` modifier (https://svelte.dev/docs#style). At the moment css completion doesn't take these styles into account.

Related to #60 and #70

**Comment by tomblachut** [comment]
Also relevant:

> If you want to make @keyframes that are accessible globally, you need to prepend your keyframe names with -global-.

> The -global- part will be removed when compiled, and the keyframe then be referenced using just my-animation-name elsewhere in your code.
