### ISSUE TITLE
Support store prefix $

### ISSUE THREAD

**Issue by bravecow** [tomblachut/svelte-intellij#75]
https://svelte.dev/docs#4_Prefix_stores_with_$_to_access_their_values

```js
import {funnelQuery} from '../stores';

<Chip color={getColor($funnelQuery, attr.id, option.value)} on:click={toggle(attr.id, option.value)}>
   {option.label}
</Chip>
```

![image](https://user-images.githubusercontent.com/988471/68078348-fbc2f080-fddc-11e9-888f-b1426c5b4257.png)

**Comment by bravecow** [comment]
Maybe a duplicate of: https://github.com/tomblachut/svelte-intellij/issues/4

**Comment by tomblachut** [comment]
Yes it is. I'm closing in favor of #4
