### ISSUE TITLE
No longer auto import after upgrading to 0.11.0

### ISSUE THREAD

**Issue by shirotech** [tomblachut/svelte-intellij#79]
Just a small regression I noticed after upgrading to 0.11.0

Before:
<img width="292" alt="Screen Shot 2019-11-04 at 3 06 30 pm" src="https://user-images.githubusercontent.com/1149825/68099140-0da7af00-ff15-11e9-8ccc-217b94869890.png">

After:
<img width="304" alt="Screen Shot 2019-11-04 at 3 07 52 pm" src="https://user-images.githubusercontent.com/1149825/68099143-126c6300-ff15-11e9-986d-129064d4e043.png">

Thanks!

**Comment by tomblachut** [comment]
Thanks for reporting!

**Comment by tomblachut** [comment]
Found a bug, hopefully I'll push new release today

**Comment by tomblachut** [comment]
Fixed in https://github.com/tomblachut/svelte-intellij/releases/tag/v0.11.1
