### ISSUE TITLE
Support namespaced components

### ISSUE THREAD

**Issue by tomblachut** [tomblachut/svelte-intellij#8]
`dev.blachut.svelte.lang.codeInsight.SvelteTagProvider#getDescriptor` should return implementation of `XmlElementDescriptor`. Could reuse or enhance `SvelteComponentTagDescriptor` if possible. Descriptor should return available props in `getAttributesDescriptors` method.

This task is unfortunately partially blocked by #2

**Comment by tomblachut** [comment]
`dev.blachut.svelte.lang.codeInsight.SvelteTagProvider#getDescriptor` should return implementation of `XmlElementDescriptor`. Could reuse or enhance `SvelteComponentTagDescriptor` if possible. Descriptor should return available props in `getAttributesDescriptors` method.

This task is unfortunately partially blocked by #2

**Comment by indigo-jay** [comment]
Is this bug referring to the following? These are components from SvelteUI (which work correctly despite the red error indications):

![image](https://user-images.githubusercontent.com/97927302/185171503-39f79c00-dbc5-4999-841b-84603a4a5bc6.png)

**Comment by tomblachut** [comment]
Migrated to [WEB-61636](https://youtrack.jetbrains.com/issue/WEB-61636) Svelte: stop marking namespaced components as unresolved
