### ISSUE TITLE
Allow style language autocompletion in lang attribute

### ISSUE THREAD

**Issue by AleksandrSl** [tomblachut/svelte-intellij#81]
Like it's done in Vue plugin
![image](https://user-images.githubusercontent.com/15820496/68193238-bd3b5a80-ffc3-11e9-891a-4f532be68d3a.png)

**Comment by AleksandrSl** [comment]
Looks like `org.jetbrains.vuejs.codeInsight.attributes.VueAttributeValueCompletionProvider`

**Comment by tomblachut** [comment]
Little update. I've debugged IDE during the weekend and got how the completions work more or less.

This should be handled soon-ish :+1:
