### ISSUE TITLE
PHPStorm ?

### ISSUE THREAD

**Issue by fsieduc** [tomblachut/svelte-intellij#82]
Hi,

any chance to have your work PHPStorm compatible ?

**Comment by tomblachut** [comment]
It should work. Is there a specific problem?

**Comment by fsieduc** [comment]
using 
PhpStorm 2018.3.1, build PS-183.4588.67. 
I can't find your pluing in the marketplace so I downloaded it (svelte-intellij-0.11.1.zip)
Installing it from disk PHPStorm says 
<img width="548" alt="Capture d’écran 2019-11-06 à 21 37 18" src="https://user-images.githubusercontent.com/7429274/68335940-b143bb80-00dd-11ea-95f5-2f86cfb938a7.png">

**Comment by tomblachut** [comment]
Sorry, you need at least version 2019.2. I'm using newer APIs in order to have enough time to release anything :)

**Comment by fsieduc** [comment]
Don't be sorry :-)
Thanx for your quick & clear help.
