### ISSUE TITLE
"Unresolved variable or type" when using script with context="module"

### ISSUE THREAD

**Issue by darrenmothersele** [tomblachut/svelte-intellij#84]
I get an error "Unresolved variable or type videoElem" with the following component.
The error appears in the IDE, but does not break the Svelte build.

```html
<video muted playsinline bind:this={videoElem}></video>

<script context="module">
    // Something happens here at module context, not for each component
</script>

<script>
    let videoElem;
</script>
```

If I move the variable declaration to the module context, or swap the order of the script blocks, then the error does not appear. Perhaps the plugin is only looking within the first script block within a component?

**Comment by tomblachut** [comment]
> Perhaps the plugin is only looking within the first script block within a component?

Yes it is :) Script tags with module context aren't supported yet, sorry.

**Comment by darrenmothersele** [comment]
Thanks!

**Comment by darrenmothersele** [comment]
Will you be rolling a new release that includes this fix? Thanks!

**Comment by tomblachut** [comment]
Yep you can grap it here before it lands in JB marketplace https://github.com/tomblachut/svelte-intellij/releases/tag/v0.12.0
