### ISSUE TITLE
variables defined in $: label are unresolved

### ISSUE THREAD

**Issue by shirotech** [tomblachut/svelte-intellij#89]
It is only resolved if you placed a `let` outside, but should still be valid to save that extra line without it.

e.g.
<img width="287" alt="Screen Shot 2019-11-17 at 9 46 06 pm" src="https://user-images.githubusercontent.com/1149825/69006505-b5949200-0983-11ea-9fbd-edee39ef268e.png">

**Comment by tomblachut** [comment]
Closing in favor of #7 

This turned out to be the hardest piece to implement because it circumvents JS analysis.
