### ISSUE TITLE
cmd-click should go to implementation instead of import

### ISSUE THREAD

**Issue by shirotech** [tomblachut/svelte-intellij#90]
@tomblachut I know this is un-released, but from latest master I've noticed a regression.

In case this is missed before releasing :)

This is happening when I cmd-click (mac) on an Element component. Before it used to go directly to the .svelte file.

In future how would you like me to report these? And apologies if you've picked this up already. Thanks.

**Comment by tomblachut** [comment]
Hah thx. I'll need to add one more class then. I was meaning to ask folks for some beta testing. 

There'll be churn in issues anyway so don't worry about it. You can also drop me a DM on Twitter if you like, same username. Or on Svelte Discord but I'm being constantly logged out automatically on my phone so it's unreliable...

**Comment by tomblachut** [comment]
@shirotech fixed. It would be great if you could test that nothing broke as a side effect.

**Comment by shirotech** [comment]
@tomblachut Thanks for looking into this very quickly, looks really good so far. Did a scan, no problems so far, but if any edge cases occur I'll sure to let you know.
