### ISSUE TITLE
Unused import warning when module used inside event and animate directives.

### ISSUE THREAD

**Issue by dnasseri** [tomblachut/svelte-intellij#92]
Hi there! Thanks for working on this plugin, I find it very useful! I found a small bug. When importing a module and using it inside a directive in a component, the import statement is greyed out and we get an "unused import warning":

Here is the relavent code
```
<script>
  import { quintOut } from 'svelte/easing';
  import { fly } from 'svelte/transition';
  import { flip } from 'svelte/animate';
</script>

<div>
    {#each items.filter((item) => item.id === active) as item (item.id)}
      <img src={item.url}
           data-carousel-index={item.id}
           alt={`carousel-image-${item.id}`}
           on:click|stopPropagation|preventDefault={handleClick}
           on:mousemove={updateCursor}
           on:mouseenter={updateCursor}
           out:fly="{{
 x: -window.innerWidth * easeDirection, opacity: 1, duration: 600, easing: quintOut,
}}"
           in:fly="{{
 x: window.innerWidth * easeDirection, opacity: 1, duration: 600, easing: quintOut,
}}"
           animate:flip
      >
    {/each}
</div>
```

You can see int the editor it is greyed out:
![private-chef-club  ~:Workspace:private-chef-club  -  :apps:marketing:ui-components:SplashCarousel svelte 2019-11-17 14-19-50](https://user-images.githubusercontent.com/8558194/69012583-5f086300-0945-11ea-92bb-e870646eb993.png)

Though it is being used here:
![private-chef-club  ~:Workspace:private-chef-club  -  :apps:marketing:ui-components:SplashCarousel svelte 2019-11-17 14-20-30](https://user-images.githubusercontent.com/8558194/69012589-747d8d00-0945-11ea-8a81-70654cdb15cd.png)

**Comment by tomblachut** [comment]
Hi! Yes, please refer to #11.
Basically every reference used in HTML attribute name so far is treated as plain text.

**Comment by dnasseri** [comment]
Sorry for opening this I didn't see that issue! Thanks again!
