### ISSUE TITLE
Wrong indentation character when pasting code

### ISSUE THREAD

**Issue by perifer** [tomblachut/svelte-intellij#94]
A project I work one indent code with spaces. When pasting code in a Svelte file with this plugin installed, the pasted code is indented with tabs instead of spaces. This also happens with code completions, like `if`

When writing the code is correctly indented with spaces.

If I instead associate .svelte files with HTML (and skip this plugin) indentation works correctly.

**Comment by bravecow** [comment]
The same bug video:

https://www.dropbox.com/s/a65x6x26huq9k85/svelte-idea.gif?dl=0

After autoformat all spaces are correct.

**Comment by tomblachut** [comment]
Let me know if issue is still occurring in [v0.13.0](https://github.com/tomblachut/svelte-intellij/releases/tag/v0.13.0)?
